export interface FrequentlyAskedQuestions {
	question: string,
	answer?: string,
}

export enum Type {
	DEPARTMENT_IN = "Department In",
	INDEPENDENT_ESTABLISHMENT_IN = "Independent Establishment In",
}

export interface GoogleEntityRelationship {
	type: Type,
	placeId: string,
}

export interface Interval {
	start?: any,
	end?: any,
}

export interface DayHour {
	openIntervals?: Interval[],
	isClosed?: boolean,
}

export interface HolidayHours {
	date: string,
	openIntervals?: Interval[],
	isClosed?: boolean,
	isRegularHours?: boolean,
}

export interface Hours {
	monday?: DayHour,
	tuesday?: DayHour,
	wednesday?: DayHour,
	thursday?: DayHour,
	friday?: DayHour,
	saturday?: DayHour,
	sunday?: DayHour,
	holidayHours?: HolidayHours[],
	reopenDate?: string,
}

export enum Type_1 {
	POSTAL_CODE = "Postal Code",
	REGION = "State/Region",
	COUNTY = "County",
	CITY = "City",
	SUBLOCALITY = "Sublocality",
}

export interface ServiceAreaPlaces {
	name?: string,
	type?: Type_1,
}

export interface Address {
	line1?: string,
	line2?: string,
	line3?: string,
	sublocality?: string,
	city?: string,
	region?: string,
	postalCode?: string,
	extraDescription?: string,
	countryCode?: string,
}

export interface ImageThumbnail {
	url: string,
	width: number,
	height: number,
}

export interface Image {
	url: string,
	width: number,
	height: number,
	thumbnails?: ImageThumbnail[],
	alternateText?: string,
}

export interface ComplexImage {
	image: Image,
	details?: string,
	description?: string,
	clickthroughUrl?: string,
}

export interface Coordinate {
	latitude?: number,
	longitude?: number,
}

export interface Video {
	url: string,
}

export interface C_aboutSectionVideo {
	title?: string,
	video?: Video,
	description?: string,
}

export interface EntityReference {
	entityId: string,
	name: string,
}

export enum C_affiliations {
	NEWYORK_PRESBYTERIAN___COLUMBIA_UNIVERSITY_IRVING_MEDICAL_CENTER = "NewYork-Presbyterian / Columbia University Irving Medical Center",
	NEWYORK_PRESBYTERIAN_LOWER_MANHATTAN_HOSPITAL = "NewYork-Presbyterian Lower Manhattan Hospital",
	NEWYORK_PRESBYTERIAN___WEILL_CORNELL_MEDICAL_CENTER = "NewYork-Presbyterian / Weill Cornell Medical Center",
	NEWYORK_PRESBYTERIAN_MORGAN_STANLEY_CHILDREN_S_HOSPITAL = "NewYork-Presbyterian Morgan Stanley Children's Hospital",
	NEWYORK_PRESBYTERIAN_ALLEN_HOSPITAL = "NewYork-Presbyterian Allen Hospital",
	NEWYORK_PRESBYTERIAN_LAWRENCE_HOSPITAL = "NewYork-Presbyterian Lawrence Hospital",
	NEWYORK_PRESBYTERIAN_KOMANSKY_CHILDREN_S_HOSPITAL = "NewYork-Presbyterian Komansky Children's Hospital",
	NEWYORK_PRESBYTERIAN_QUEENS_HOSPITAL = "NewYork-Presbyterian Queens Hospital",
	NEWYORK_PRESBYTERIAN_HUDSON_VALLEY_HOSPITAL = "NewYork-Presbyterian Hudson Valley Hospital",
	NEWYORK_PRESBYTERIAN_BROOKLYN_METHODIST_HOSPITAL = "NewYork-Presbyterian Brooklyn Methodist Hospital",
	NEWYORK_PRESBYTERIAN_ALEXANDRA_COHEN_HOSPITAL_FOR_WOMEN_AND_NEWBORNS = "NewYork-Presbyterian Alexandra Cohen Hospital for Women and Newborns",
	NEWYORK_PRESBYTERIAN_WESTCHESTER_BEHAVIORAL_HEALTH_CENTER = "NewYork-Presbyterian Westchester Behavioral Health Center",
	OCH_SPINE_AT_NEWYORK_PRESBYTERIAN = "Och Spine At NewYork-Presbyterian",
	NEWYORK_PRESBYTERIAN_DAVID_H__KOCH_CENTER = "NewYork-Presbyterian David H. Koch Center",
	NEWYORK_PRESBYTERIAN_WESTCHESTER_HOSPITAL = "NewYork-Presbyterian Westchester Hospital",
	NEWYORK_PRESBYTERIAN_WESTCHESTER = "NewYork-Presbyterian Westchester",
}

export enum C_boardCertifiedSpecialties {
	OPHTHALMOLOGY = "Ophthalmology",
	INTERNAL_MEDICINE = "Internal Medicine",
	CARDIOVASCULAR_DISEASE = "Cardiovascular Disease",
	PEDIATRICS = "Pediatrics",
	PEDIATRIC_EMERGENCY_MEDICINE = "Pediatric Emergency Medicine",
	EMERGENCY_MEDICINE = "Emergency Medicine",
	DIAGNOSTIC_RADIOLOGY = "Diagnostic Radiology",
	OBSTETRICS_AND_GYNECOLOGY = "Obstetrics and Gynecology",
	REPRODUCTIVE_ENDOCRINOLOGY_AND_INFERTILITY = "Reproductive Endocrinology and Infertility",
	CLINICAL_INFORMATICS = "Clinical Informatics",
	CRITICAL_CARE_MEDICINE___PEDIATRIC = "Critical Care Medicine - Pediatric",
	NEUROLOGY_WITH_SPECIAL_QUALIFICATION_IN_CHILD_NEUROLOGY = "Neurology with Special Qualification in Child Neurology",
	CHILD_NEUROLOGY = "Child Neurology",
	HEMATOLOGY = "Hematology",
	ANATOMIC_PATHOLOGY_AND_CLINICAL_PATHOLOGY = "Anatomic Pathology and Clinical Pathology",
	PUBLIC_HEALTH_AND_GENERAL_PREVENTIVE_MEDICINE = "Public Health and General Preventive Medicine",
	FAMILY_MEDICINE = "Family Medicine",
	RADIOLOGY__VASCULAR_INTERVENTIONAL = "Radiology, Vascular/Interventional",
	UROLOGY = "Urology",
	PSYCHIATRY = "Psychiatry",
	GERIATRIC_PSYCHIATRY = "Geriatric Psychiatry",
	GERIATRIC_MEDICINE = "Geriatric Medicine",
	GENERAL_SURGERY = "General Surgery",
	THORACIC_SURGERY = "Thoracic Surgery",
	ENDOCRINOLOGY__DIABETES_AND_METABOLISM = "Endocrinology, Diabetes and Metabolism",
	NEUROMUSCULAR_MEDICINE = "Neuromuscular Medicine",
	GASTROENTEROLOGY = "Gastroenterology",
	PEDIATRIC_ENDOCRINOLOGY = "Pediatric Endocrinology",
	PEDIATRIC_PULMONOLOGY = "Pediatric Pulmonology",
	ANESTHESIOLOGY = "Anesthesiology",
	CRITICAL_CARE_MEDICINE = "Critical Care Medicine",
	SURGERY___COLON_AND_RECTAL_SURGERY = "Surgery - Colon and Rectal Surgery",
	HOSPICE_AND_PALLIATIVE_MEDICINE = "Hospice and Palliative Medicine",
	MEDICAL_ONCOLOGY = "Medical Oncology",
	ADVANCED_HEART_FAILURE_AND_TRANSPLANT_CARDIOLOGY = "Advanced Heart Failure and Transplant Cardiology",
	CHILD_AND_ADOLESCENT_PSYCHIATRY = "Child and Adolescent Psychiatry",
	PHYSICAL_MEDICINE_AND_REHABILITATION = "Physical Medicine and Rehabilitation",
	PAIN_MEDICINE = "Pain Medicine",
	NEUROLOGY = "Neurology",
	PEDIATRIC_SURGERY = "Pediatric Surgery",
	PLASTIC_SURGERY = "Plastic Surgery",
	NEURORADIOLOGY = "Neuroradiology",
	ORTHOPEDIC_SURGERY = "Orthopedic Surgery",
	ANATOMIC_PATHOLOGY = "Anatomic Pathology",
	ENDOCRINOLOGY = "Endocrinology",
	PATHOLOGY_ANATOMIC_PATHOLOGY_CLINICAL = "Pathology-Anatomic/Pathology-Clinical",
	OBGYN___MATERNAL_FETAL_MEDICINE = "OBGYN - Maternal-Fetal Medicine",
	CARDIOTHORACIC_SURGERY = "Cardiothoracic Surgery",
	SURGERY = "Surgery",
	THORACIC_AND_CARDIAC_SURGERY = "Thoracic and Cardiac Surgery",
	PEDIATRIC_CARDIOLOGY = "Pediatric Cardiology",
	CLINICAL_GENETICS_AND_GENOMICS__MD_ = "Clinical Genetics and Genomics (MD)",
	CLINICAL_NEUROPSYCHOLOGY = "Clinical Neuropsychology",
	CYTOPATHOLOGY = "Cytopathology",
	PATHOLOGY___HEMATOLOGY = "Pathology - Hematology",
	PATHOLOGY___MOLECULAR_GENETIC = "Pathology - Molecular Genetic",
	CARDIAC_SURGERY = "Cardiac Surgery",
	PULMONARY_DISEASE_MEDICINE = "Pulmonary Disease Medicine",
	NEPHROLOGY = "Nephrology",
	PATHOLOGY___ANATOMIC = "Pathology - Anatomic",
	RADIOLOGY___VASCULAR_AND_INTERVENTIONAL_RADIOLOGY = "Radiology - Vascular and Interventional Radiology",
	RADIOLOGY___DIAGNOSTIC_RADIOLOGY = "Radiology - Diagnostic Radiology",
	RADIOLOGY___NEURORADIOLOGY = "Radiology - Neuroradiology",
	PEDIATRIC_REHABILITATION_MEDICINE = "Pediatric Rehabilitation Medicine",
	PEDIATRIC_HEMATOLOGY_ONCOLOGY = "Pediatric Hematology-Oncology",
	SPORTS_MEDICINE = "Sports Medicine",
	CLINICAL_CARDIAC_ELECTROPHYSIOLOGY = "Clinical Cardiac Electrophysiology",
	PULMONARY_DISEASE = "Pulmonary Disease",
	SLEEP_MEDICINE = "Sleep Medicine",
	ALLERGY_AND_IMMUNOLOGY = "Allergy and Immunology",
	PSYCHOSOMATIC_MEDICINE = "Psychosomatic Medicine",
	VASCULAR_SURGERY = "Vascular Surgery",
	SURGERY__GENERAL = "Surgery, General",
	ADULT_CONGENITAL_HEART_DISEASE = "Adult Congenital Heart Disease",
	AMERICAN_MIDWIFERY_CERTIFICATION_BOARD = "American Midwifery Certification Board",
	INFECTIOUS_DISEASE = "Infectious Disease",
	PEDIATRIC_RADIOLOGY = "Pediatric Radiology",
	MATERNAL_FETAL_MEDICINE = "Maternal-Fetal Medicine",
	PEDIATRIC_ANESTHESIOLOGY = "Pediatric Anesthesiology",
	PEDIATRIC_CRITICAL_CARE_MEDICINE = "Pediatric Critical Care Medicine",
	PATHOLOGY___PEDIATRIC = "Pathology - Pediatric",
	PEDIATRIC_INFECTIOUS_DISEASES = "Pediatric Infectious Diseases",
	PEDIATRIC_GASTROENTEROLOGY = "Pediatric Gastroenterology",
	FORENSIC_PSYCHIATRY = "Forensic Psychiatry",
	FEMALE_PELVIC_MEDICINE_AND_RECONSTRUCTIVE_SURGERY = "Female Pelvic Medicine and Reconstructive Surgery",
	PEDIATRIC_RHEUMATOLOGY = "Pediatric Rheumatology",
	DERMATOLOGY = "Dermatology",
	PEDIATRIC_ALLERGY_AND_IMMUNOLOGY = "Pediatric Allergy and Immunology",
	REPRODUCTIVE_ENDOCRINOLOGY_INFERTILITY = "Reproductive Endocrinology/Infertility",
	VASCULAR_NEUROLOGY = "Vascular Neurology",
	PATHOLOGY___CLINICAL = "Pathology - Clinical",
	NEUROLOGICAL_SURGERY = "Neurological Surgery",
	PEDIATRIC_NEPHROLOGY = "Pediatric Nephrology",
	ADDICTION_PSYCHIATRY = "Addiction Psychiatry",
	VASCULAR_AND_INTERVENTIONAL_RADIOLOGY = "Vascular and Interventional Radiology",
	RHEUMATOLOGY = "Rheumatology",
	NUCLEAR_MEDICINE = "Nuclear Medicine",
	CHILD_PSYCHIATRY = "Child Psychiatry",
	GYNECOLOGIC_ONCOLOGY = "Gynecologic Oncology",
	CLINICAL_NEUROPHYSIOLOGY = "Clinical Neurophysiology",
	CLINICAL_PATHOLOGY = "Clinical Pathology",
	BLOOD_BANKING_TRANSFUSION_MEDICINE = "Blood Banking/Transfusion Medicine",
	SURGICAL_CRITICAL_CARE = "Surgical Critical Care",
	NEUROPATHOLOGY = "Neuropathology",
	OBGYN___OBSTETRICS_AND_GYNECOLOGY = "OBGYN - Obstetrics and Gynecology",
	OTOLARYNGOLOGY = "Otolaryngology",
	PODIATRIC_MEDICINE = "Podiatric Medicine",
	FOOT_AND_ANKLE_SURGERY = "Foot and Ankle Surgery",
	RECONSTRUCTIVE_REARFOOT_ANKLE = "Reconstructive Rearfoot/Ankle",
	HEMATOLOGY_AND_MEDICAL_ONCOLOGY = "Hematology and Medical Oncology",
	PERIODONTOLOGY_AND_DENTAL_IMPLANT_SURGERY = "Periodontology and Dental Implant Surgery",
	ANESTHESIOLOGY_CRITICAL_CARE_MEDICINE = "Anesthesiology Critical Care Medicine",
	NEUROTOLOGY = "Neurotology",
	PEDIATRIC_DENTISTRY = "Pediatric Dentistry",
	PEDIATRIC_ANESTHESIA = "Pediatric Anesthesia",
	NEONATAL_PERINATAL_MEDICINE = "Neonatal-Perinatal Medicine",
	RADIATION_ONCOLOGY = "Radiation Oncology",
	COLON_AND_RECTAL_SURGERY = "Colon and Rectal Surgery",
	GYNECOLOGY = "Gynecology",
	_OBSTETRICS_AND_GYNECOLOGY_ = "(Obstetrics and Gynecology)",
	INTERVENTIONAL_CARDIOLOGY = "Interventional Cardiology",
	SURGERY__THORACIC_CARDIOVASCULAR = "Surgery, Thoracic Cardiovascular",
	CONGENITAL_CARDIAC_SURGERY = "Congenital Cardiac Surgery",
	DEVELOPMENTAL_BEHAVIORAL_PEDIATRICS = "Developmental-Behavioral Pediatrics",
	ECHOCARDIOGRAPHY = "Echocardiography",
	ADOLESCENT_MEDICINE = "Adolescent Medicine",
	CHILD_ABUSE_PEDIATRICS = "Child Abuse Pediatrics",
	NEUROLOGY_WITH_SPECIAL_QUAL_IN_CHILD_NEUROLOGY = "Neurology with Special Qual in Child Neurology",
	EPILEPSY = "Epilepsy",
	MATERNAL_AND_FETAL_MEDICINE = "Maternal and Fetal Medicine",
	PEDIATRIC_TRANSPLANT_HEPATOLOGY = "Pediatric Transplant Hepatology",
	BARIATRIC_SURGERY = "Bariatric Surgery",
	NEONATAL_PERINATAL_MEDICINE__PEDIATRIC_ = "Neonatal-Perinatal Medicine (Pediatric)",
	AMERICAN_NURSES_CREDENTIALING_CENTER__ANCC__IN_ADULT_HEALTH = "American Nurses Credentialing Center (ANCC) in Adult Health",
	PULMONARY_MEDICINE = "Pulmonary Medicine",
	PERIODONTOLOGY = "Periodontology",
	AMERICAN_NURSES_CREDENTIALING_CENTER__ANCC_ = "American Nurses Credentialing Center (ANCC)",
	SURGERY___GENERAL_SURGERY = "Surgery - General Surgery",
	DENTISTRY = "Dentistry",
	AMERICAN_NURSES_CREDENTIALING_CENTER = "American Nurses Credentialing Center",
	CARDIOLOGY = "Cardiology",
	ORTHOPEDIC_SPORTS_MEDICINE = "Orthopedic Sports Medicine",
	CLINICAL_MOLECULAR_GENETICS_AND_GENOMICS = "Clinical Molecular Genetics and Genomics",
	ONCOLOGY = "Oncology",
	ORAL_AND_MAXILLOFACIAL_SURGERY = "Oral and Maxillofacial Surgery",
	TRANSPLANT_HEPATOLOGY = "Transplant Hepatology",
	SURGERY__COLON_AND_RECTAL = "Surgery, Colon and Rectal",
	PREVENTIVE_MEDICINE = "Preventive Medicine",
	AMERICAN_BOARD_OF_INTERNAL_MEDICINE = "American Board of Internal Medicine",
	AMERICAN_BOARD_OF_INTERNAL_MEDICINE___GERIATRIC_MEDICINE = "American Board of Internal Medicine - Geriatric Medicine",
	PEDIATRIC_DERMATOLOGY = "Pediatric Dermatology",
	CLINICAL_BIOCHEMICAL_GENETICS = "Clinical Biochemical Genetics",
	MOLECULAR_GENETIC_PATHOLOGY = "Molecular Genetic Pathology",
	PEDIATRICS_CRITICAL_CARE_MEDICINE = "Pediatrics Critical Care Medicine",
	RADIOLOGY = "Radiology",
	SURGERY_OF_THE_HAND = "Surgery of the Hand",
	CARDIOVASCULAR_DISEASES = "Cardiovascular Diseases",
	NUCLEAR_CARDIOLOGY = "Nuclear Cardiology",
	NEURODEVELOPMENTAL_DISABILITIES = "Neurodevelopmental Disabilities",
	CRITICAL_CARE = "Critical Care",
	_PEDIATRICS = "(Pediatrics",
	MEDICAL_TOXICOLOGY = "Medical Toxicology",
	ORAL___MAXILLOFACIAL_RADIOLOGY = "Oral & Maxillofacial Radiology",
	ORAL___MAXILLOFACIAL_PATHOLOGY = "Oral & Maxillofacial Pathology",
	AM_BD_PATH__SUB__BLOOD_BANKING_TRANSFUSION_MEDICINE_ = "Am Bd Path (sub: Blood Banking/Transfusion Medicine)",
	BOARD_CERTIFICATIONS = "Board Certifications",
	ORAL_AND_MAXILLOFACIAL_PATHOLOGY = "Oral and Maxillofacial Pathology",
	OBSTETRICS___GYNECOLOGY = "Obstetrics & Gynecology",
	DIABETES__ENDOCRINOLOGY____METABOLISM_OBESITY_MEDICINE = "Diabetes, Endocrinology, & Metabolism Obesity Medicine",
	FAMILY_NURSE_PRACTITIONER = "Family Nurse Practitioner",
	PEDIATRIC_NURSE_PRACTITIONER_PRIMARY_CARE = "Pediatric Nurse Practitioner Primary Care",
	PEDIATRIC_HOSPITAL_MEDICINE = "Pediatric Hospital Medicine",
	PNCB_CERTIFIED_PEDIATRIC_NURSE = "PNCB Certified Pediatric Nurse",
	AMERICAN_BOARD_OF_FAMILY_MEDICINE = "American Board of Family Medicine",
	ABFAS__FOOT_AND_ANKLE_SURGERY_ = "ABFAS (Foot and Ankle Surgery)",
	AM_BD_INT_MED__INTERNAL_MEDICINE_ = "Am Bd Int Med (Internal Medicine)",
	DERMATOPATHOLOGY = "Dermatopathology",
	ORTHOPAEDIC_SURGERY = "Orthopaedic Surgery",
	INTERVENTIONAL_RADIOLOGY = "Interventional Radiology",
	PEDIATRIC_UROLOGY = "Pediatric Urology",
	OBGYN___GYNECOLOGIC_ONCOLOGY = "OBGYN - Gynecologic Oncology",
}

export interface C_centersInstitutesAndPrograms {
	displayName: string,
	externalCode: string,
}

export interface C_cTA1LinkText {
	cta1Text?: string,
	cta1Link?: string,
}

export interface C_cTA2LinkText {
	cta1Text?: string,
	cta1Link?: string,
}

export interface C_cUIMCAboutSectionVideo {
	title?: string,
	video?: Video,
	description?: string,
}

export interface C_cUIMCApptTile1 {
	title?: string,
	description?: string,
	input1?: string,
	input2?: string,
	input3?: string,
}

export interface Cta {
	cta1Text?: string,
	cta1Link?: string,
}

export interface C_cUIMCApptTile2 {
	title?: string,
	description?: string,
	cta?: Cta,
}

export interface C_cUIMCApptTile3 {
	title?: string,
	description?: string,
	cta?: Cta,
}

export interface C_cUIMCCTA1 {
	cta1Text?: string,
	cta1Link?: string,
}

export interface C_cUIMCInsuranceList {
	title?: string,
	list?: string[],
}

export enum C_cUIMCInsurancesFilter {
	UNITEDHEALTHCARE = "UnitedHealthcare",
	CIGNA = "CIGNA",
	FIDELIS_CARE = "Fidelis Care",
	AMIDA_CARE = "Amida Care",
	MEDICARE = "Medicare",
	EMBLEM_GHI = "Emblem/GHI",
	AGEWELL = "AgeWell",
	AFFINITY_HEALTH_PLAN = "Affinity Health Plan",
	QUALITY_HEALTH_MANAGEMENT = "Quality Health Management",
	AETNA = "AETNA",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD = "Empire Blue Cross/Blue Shield",
	OXFORD_HEALTH_PLANS = "Oxford Health Plans",
	EMBLEM_HIP = "Emblem/Hip",
	HEALTHFIRST = "Healthfirst",
	RIVERSPRING = "RiverSpring",
	MVP_HEALTH_CARE = "MVP Health Care",
	LOCAL_1199 = "Local 1199",
	MAGNACARE__NATIONAL_ = "Magnacare (National)",
	MULTIPLAN = "Multiplan",
	WELLCARE = "WellCare",
	VNSNY_CHOICE = "VNSNY CHOICE",
	ELDERPLAN = "Elderplan",
	COVENTRY_HEALTH_CARE = "Coventry Health Care",
	HEALTHPLEX = "Healthplex",
	CHP_STUDENT_HEALTH = "CHP Student Health",
	WORKERS_COMPENSATION = "Workers Compensation",
	AMERIHEALTH_OF_NEW_JERSEY = "AmeriHealth of New Jersey",
	HORIZON_BLUE_CROSS_BLUE_SHIELD = "Horizon Blue Cross Blue Shield",
	AMERIGROUP_OF_NEW_JERSEY = "Amerigroup of New Jersey",
	QUALCARE = "QualCare",
	CONNECTICARE = "Connecticare",
	UNICARE = "Unicare",
	_1199_NATIONAL_BENEFIT_FUND = "1199 National Benefit Fund",
	ANTHEM_BLUE_CROSS_BLUE_SHIELD = "Anthem Blue Cross Blue Shield",
	CAPITAL_DISTRICT_PHYSICIAN_HEALTH_PLAN__CDPHP_ = "Capital District Physician Health Plan (CDPHP)",
	CONSUMER_HEALTH_NETWORK__CHN_ = "Consumer Health Network (CHN)",
	DEVON_HEALTH_SERVICES = "Devon Health Services",
	DENTAQUEST = "DentaQuest",
	MEDICAID = "Medicaid",
	MARCH_VISION = "March Vision",
	AARP = "AARP",
	TRICARE = "TRICARE",
	CAMBRIDGE_NETWORK = "Cambridge Network",
	HEALTH_INSURANCE_PLAN_OF_NY__HIP_ = "Health Insurance Plan of NY (HIP)",
	UNITED_HEALTHCARE = "United Healthcare",
	GHI = "GHI",
	AETNA___WEILL_CORNELL = "Aetna - Weill Cornell",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_HEALTHPLUS = "Empire Blue Cross/Blue Shield Healthplus",
	AETNA___NYP = "Aetna - NYP",
	GUARDIAN = "Guardian",
}

export enum C_cUIMCPrimarySpecialty {
	OPHTHALMOLOGY = "Ophthalmology",
	MEDICAL_RETINA = "Medical Retina",
	CARDIOVASCULAR_DISEASE = "Cardiovascular Disease",
	INTERNAL_MEDICINE = "Internal Medicine",
	HOSPITAL_MEDICINE = "Hospital Medicine",
	CATARACT_SURGERY = "Cataract Surgery",
	GLAUCOMA = "Glaucoma",
	CORNEA___EXTERNAL_DISORDERS = "Cornea & External Disorders",
	PRIMARY_CARE = "Primary Care",
	PEDIATRICS = "Pediatrics",
	PEDIATRICIAN__GENERAL_PEDIATRICS_ = "Pediatrician (General Pediatrics)",
	EMERGENCY_MEDICINE = "Emergency Medicine",
	PEDIATRIC_EMERGENCY_MEDICINE = "Pediatric Emergency Medicine",
	RADIOLOGY = "Radiology",
	DIAGNOSTIC_RADIOLOGY = "Diagnostic Radiology",
	OBSTETRICS_AND_GYNECOLOGY = "Obstetrics and Gynecology",
	REPRODUCTIVE_ENDOCRINOLOGY_INFERTILITY = "Reproductive Endocrinology/Infertility",
	INFECTIOUS_DISEASE = "Infectious Disease",
	PEDIATRIC_CRITICAL_CARE_MEDICINE = "Pediatric Critical Care Medicine",
	NEUROLOGY_WITH_SPECIAL_QUALIFICATION_IN_CHILD_NEUROLOGY = "Neurology with Special Qualification in Child Neurology",
	PEDIATRIC_NEUROLOGY = "Pediatric Neurology",
	HEMATOLOGY = "Hematology",
	PATHOLOGY___ANATOMIC___CLINICAL = "Pathology - Anatomic & Clinical",
	FAMILY_MEDICINE = "Family Medicine",
	VASCULAR_AND_INTERVENTIONAL_RADIOLOGY = "Vascular and Interventional Radiology",
	UROLOGY = "Urology",
	PSYCHOLOGY = "Psychology",
	CHILD_AND_ADOLESCENT_PSYCHOLOGY = "Child and Adolescent Psychology",
	GERIATRIC_PSYCHIATRY = "Geriatric Psychiatry",
	PSYCHIATRY = "Psychiatry",
	GERIATRIC_MEDICINE = "Geriatric Medicine",
	NURSE_PRACTITIONER = "Nurse Practitioner",
	ENDOCRINOLOGY__DIABETES_AND_METABOLISM = "Endocrinology, Diabetes and Metabolism",
	DENTISTRY = "Dentistry",
	COSMETIC_DENTISTRY = "Cosmetic Dentistry",
	BARIATRIC_SURGERY = "Bariatric Surgery",
	GENERAL_SURGERY = "General Surgery",
	NEUROMUSCULAR_MEDICINE = "Neuromuscular Medicine",
	GASTROENTEROLOGY = "Gastroenterology",
	CANCER_CARE = "Cancer Care",
	PEDIATRIC_ENDOCRINOLOGY = "Pediatric Endocrinology",
	ENDOCRINOLOGY = "Endocrinology",
	PEDIATRIC_PULMONOLOGY = "Pediatric Pulmonology",
	PULMONOLOGY = "Pulmonology",
	ANESTHESIOLOGY = "Anesthesiology",
	CRITICAL_CARE_MEDICINE = "Critical Care Medicine",
	COLON_AND_RECTAL_SURGERY = "Colon and Rectal Surgery",
	SURGERY = "Surgery",
	PEDIATRIC_UROLOGY = "Pediatric Urology",
	NEONATOLOGY = "Neonatology",
	HOSPICE_AND_PALLIATIVE_MEDICINE = "Hospice and Palliative Medicine",
	MEDICAL_ONCOLOGY = "Medical Oncology",
	CLINICAL_INFORMATICS = "Clinical Informatics",
	ADVANCED_HEART_FAILURE_AND_TRANSPLANT_CARDIOLOGY = "Advanced Heart Failure and Transplant Cardiology",
	INTERVENTIONAL_CARDIOLOGY = "Interventional Cardiology",
	CHILD_AND_ADOLESCENT_PSYCHIATRY = "Child and Adolescent Psychiatry",
	BREAST___SOFT_TISSUE_SURGERY = "Breast & Soft Tissue Surgery",
	PHYSICAL_MEDICINE_AND_REHABILITATION = "Physical Medicine and Rehabilitation",
	NEUROLOGY = "Neurology",
	PLASTIC___RECONSTRUCTIVE_SURGERY = "Plastic & Reconstructive Surgery",
	ORTHOPEDIC_SURGERY = "Orthopedic Surgery",
	SPINE_SURGERY = "Spine Surgery",
	ORTHOPEDIC_SPINE_SURGERY = "Orthopedic Spine Surgery",
	PATHOLOGY___ANATOMIC = "Pathology - Anatomic",
	PEDIATRIC_HOSPITAL_MEDICINE = "Pediatric Hospital Medicine",
	RHEUMATOLOGY = "Rheumatology",
	PEDIATRIC_CONGENITAL_CARDIAC_SURGERY = "Pediatric/Congenital Cardiac Surgery",
	MATERNAL___FETAL_MEDICINE = "Maternal & Fetal Medicine",
	THORACIC_AND_CARDIAC_SURGERY = "Thoracic and Cardiac Surgery",
	CARDIAC_SURGERY = "Cardiac Surgery",
	GENERAL_OPHTHALMOLOGY = "General Ophthalmology",
	THORACIC_SURGERY = "Thoracic Surgery",
	RECONSTRUCTIVE_UROLOGY = "Reconstructive Urology",
	CLINICAL_GENETICS_AND_GENOMICS__MD_ = "Clinical Genetics and Genomics (MD)",
	PEDIATRIC_CARDIOLOGY = "Pediatric Cardiology",
	NEUROPSYCHOLOGY = "Neuropsychology",
	CYTOPATHOLOGY = "Cytopathology",
	GYNECOLOGIC_ONCOLOGY = "Gynecologic Oncology",
	PEDIATRIC_SURGERY = "Pediatric Surgery",
	HAND__ELBOW___MICROVASCULAR = "Hand, Elbow & Microvascular",
	PATHOLOGY___HEMATOLOGY = "Pathology - Hematology",
	PATHOLOGY___MOLECULAR_GENETIC = "Pathology - Molecular Genetic",
	GENETIC_COUNSELING = "Genetic Counseling",
	PANCREAS___HEPATOBILIARY_SURGERY = "Pancreas & Hepatobiliary Surgery",
	PEDIATRIC_INFECTIOUS_DISEASES = "Pediatric Infectious Diseases",
	PAIN_MEDICINE_MANAGEMENT = "Pain Medicine/Management",
	INTERVENTIONAL_SPINE_CARE = "Interventional Spine Care",
	NEPHROLOGY = "Nephrology",
	PEDIATRIC_HEMATOLOGY_ONCOLOGY = "Pediatric Hematology-Oncology",
	NEURORADIOLOGY = "Neuroradiology",
	PEDIATRIC_REHABILITATION_MEDICINE = "Pediatric Rehabilitation Medicine",
	SPORTS_MEDICINE = "Sports Medicine",
	SHOULDER__ELBOW___SPORTS_MEDICINE = "Shoulder, Elbow & Sports Medicine",
	PEDIATRIC_ORTHOPEDICS = "Pediatric Orthopedics",
	ELECTROPHYSIOLOGY_CARDIOLOGY = "Electrophysiology Cardiology",
	UVEITIS = "Uveitis",
	VASCULAR_SURGERY = "Vascular Surgery",
	SLEEP_MEDICINE = "Sleep Medicine",
	ALLERGY_AND_IMMUNOLOGY = "Allergy and Immunology",
	PEDIATRIC_ALLERGY_AND_IMMUNOLOGY = "Pediatric Allergy and Immunology",
	TRANSPLANT_SURGERY = "Transplant Surgery",
	KIDNEY_TRANSPLANT_SURGERY = "Kidney Transplant Surgery",
	PHYSICAL_THERAPY = "Physical Therapy",
	PERIODONTICS = "Periodontics",
	PEDIATRIC_RADIOLOGY = "Pediatric Radiology",
	PEDIATRIC_ANESTHESIOLOGY = "Pediatric Anesthesiology",
	PEDIATRIC_GASTROENTEROLOGY = "Pediatric Gastroenterology",
	FEMALE_PELVIC_MEDICINE_AND_RECONSTRUCTIVE_SURGERY = "Female Pelvic Medicine and Reconstructive Surgery",
	UROGYNECOLOGY = "Urogynecology",
	PEDIATRIC_RHEUMATOLOGY = "Pediatric Rheumatology",
	DERMATOLOGY = "Dermatology",
	UROLOGIC_ONCOLOGY = "Urologic Oncology",
	AUDIOLOGY = "Audiology",
	BLOOD_AND_MARROW_STEM_CELL_TRANSPLANTATION = "Blood and Marrow Stem Cell Transplantation",
	PATHOLOGY___CLINICAL = "Pathology - Clinical",
	NEUROLOGICAL_SURGERY = "Neurological Surgery",
	PEDIATRIC_NEPHROLOGY = "Pediatric Nephrology",
	CLINICAL_NEUROPHYSIOLOGY = "Clinical Neurophysiology",
	WOMEN_S_MENTAL_HEALTH = "Women's Mental Health",
	ADDICTION_PSYCHIATRY = "Addiction Psychiatry",
	TRAUMA = "Trauma",
	NUCLEAR_MEDICINE = "Nuclear Medicine",
	BLOOD_BANKING_TRANSFUSION_MEDICINE = "Blood Banking/Transfusion Medicine",
	SURGICAL_CRITICAL_CARE = "Surgical Critical Care",
	ORTHOPEDIC_ONCOLOGY = "Orthopedic Oncology",
	NEUROPATHOLOGY = "Neuropathology",
	OTOLARYNGOLOGY_HEAD___NECK_SURGERY = "Otolaryngology-Head & Neck Surgery",
	NEUROPSYCHIATRY = "Neuropsychiatry",
	LIVER___ABDOMINAL_TRANSPLANT_SURGERY = "Liver & Abdominal Transplant Surgery",
	NEURO_ONCOLOGY = "Neuro-Oncology",
	PEDIATRIC_DENTISTRY = "Pediatric Dentistry",
	ORTHODONTICS = "Orthodontics",
	RHINOLOGY = "Rhinology",
	NEUROTOLOGY = "Neurotology",
	STROKE___CEREBROVASCULAR_NEUROLOGY = "Stroke & Cerebrovascular Neurology",
	PEDIATRIC_OTOLARYNGOLOGY = "Pediatric Otolaryngology",
	NEONATAL_PERINATAL_MEDICINE = "Neonatal-Perinatal Medicine",
	RADIATION_ONCOLOGY = "Radiation Oncology",
	HIP___KNEE_RECONSTRUCTION = "Hip & Knee Reconstruction",
	PEDIATRIC_OPHTHALMOLOGY = "Pediatric Ophthalmology",
	PROSTHODONTICS = "Prosthodontics",
	PODIATRY = "Podiatry",
	SURGICAL_ONCOLOGY = "Surgical Oncology",
	RETINAL___VITREORETINAL_SURGERY = "Retinal & Vitreoretinal Surgery",
	ADOLESCENT_MEDICINE = "Adolescent Medicine",
	CRITICAL_CARE_NEUROLOGY = "Critical Care Neurology",
	HEMATOLOGY_ONCOLOGY = "Hematology/Oncology",
	PEDIATRIC_SLEEP_MEDICINE = "Pediatric Sleep Medicine",
	SOCIAL_WORKER = "Social Worker",
	PEDIATRIC_TRANSPLANT_HEPATOLOGY = "Pediatric Transplant Hepatology",
	OPTOMETRY = "Optometry",
	TRANSPLANT_HEPATOLOGY = "Transplant Hepatology",
	ENDOCRINE_SURGERY = "Endocrine Surgery",
	NEUROLOGICAL_SPINE_SURGERY = "Neurological Spine Surgery",
	ENDODONTICS = "Endodontics",
	MINIMALLY_INVASIVE_GYNECOLOGIC_SURGERY = "Minimally Invasive Gynecologic Surgery",
	ORTHOPEDIC_SPORTS_MEDICINE = "Orthopedic Sports Medicine",
	ORTHOGNATHIC_SURGERY = "Orthognathic Surgery",
	ORAL_AND_MAXILLOFACIAL_SURGERY = "Oral and Maxillofacial Surgery",
	PEDIATRIC_NEUROLOGICAL_SURGERY = "Pediatric Neurological Surgery",
	PREVENTIVE_MEDICINE = "Preventive Medicine",
	PEDIATRIC_DERMATOLOGY = "Pediatric Dermatology",
	NEUROENDOCRINOLOGY = "Neuroendocrinology",
	PEDIATRIC_THORACIC_SURGERY = "Pediatric Thoracic Surgery",
	FOOT___ANKLE = "Foot & Ankle",
	NEURO_OPHTHALMOLOGY = "Neuro-Ophthalmology",
	OPHTHALMIC_ONCOLOGY = "Ophthalmic Oncology",
	ADULT_CONGENITAL_HEART_DISEASE = "Adult Congenital Heart Disease",
	ELECTRODIAGNOSTIC_MEDICINE = "Electrodiagnostic Medicine",
	LGBTQ_MENTAL_HEALTH = "LGBTQ Mental Health",
	ORAL_AND_MAXILLOFACIAL_RADIOLOGY = "Oral and Maxillofacial Radiology",
	OPHTHALMIC_GENETICS = "Ophthalmic Genetics",
	ORAL_PATHOLOGY = "Oral Pathology",
	ENDOUROLOGY = "Endourology",
	SPEECH_LANGUAGE_PATHOLOGY = "Speech-Language Pathology",
	DERMATOPATHOLOGY = "Dermatopathology",
	OPHTHALMIC_PLASTIC___RECONSTRUCTIVE_SURGERY = "Ophthalmic Plastic & Reconstructive Surgery",
}

export interface C_educationInfo {
	type?: string,
	organization?: string,
	year?: string,
}

export enum C_expertiseFilter {
}

export interface C_grants {
	title?: string,
	subtitle?: string,
}

export enum C_groupCode {
	NYP = "NYP",
	CORNELL = "Cornell",
	CLINICIAN = "Clinician",
	ACN = "ACN",
	ACN_WEB = "ACN-Web",
	NYP_CACTUS = "NYP Cactus",
	EPIC = "Epic",
	COLUMBIA = "Columbia",
	RESEARCHER = "Researcher",
	COLUMBIA_INTELLICRED = "Columbia Intellicred",
	NYPMG_B = "NYPMG-B",
	NYPMG = "NYPMG",
	NYPMG_Q = "NYPMG-Q",
	NYPMG_HV = "NYPMG-HV",
	NYPMG_WEST = "NYPMG-West",
}

export enum C_hospitalAndMedGroupLocator {
	MEDICAL_GROUP_BROOKLYN = "Medical Group Brooklyn",
	MEDICAL_GROUP_HUDSON_VALLEY = "Medical Group Hudson Valley",
	MEDICAL_GROUP_QUEENS = "Medical Group Queens",
	MEDICAL_GROUP_WESTCHESTER = "Medical Group Westchester",
}

export enum C_insurancesFilter {
	_1199_NATIONAL_BENEFIT_FUND = "1199 National Benefit Fund",
	AARP = "AARP",
	AETNA = "AETNA",
	AETNA_NEW_YORK_SIGNATURE = "Aetna New York Signature",
	AETNA_SIGNATURE_ADMINISTRATORS = "Aetna Signature Administrators",
	AETNA_STUDENT_HEALTH = "Aetna Student Health",
	AETNA_US_HEALTH_CARE = "Aetna US Health Care",
	AETNA_WEILL_CORNELL_MEDICINE = "Aetna Weill Cornell Medicine",
	AFFINITY = "Affinity",
	AFFINITY_ACCESS = "Affinity Access",
	AFFINITY_ESSENTIAL = "Affinity Essential",
	AFFINITY_HEALTH_PLAN = "Affinity Health Plan",
	ALL_AMERICAN_HEALTH_ENTERPRISES = "All American Health Enterprises",
	AMERIGROUP = "Amerigroup",
	AMERIHEALTH = "AmeriHealth",
	AMIDA_CARE = "Amida Care",
	ANTHEM_BLUE_CROSS_BLUE_SHIELD = "Anthem Blue Cross Blue Shield",
	BEECHSTREET = "Beechstreet",
	BEECHSTREET_MEDICHOICE = "Beechstreet Medichoice",
	CAMBRIDGE_NETWORK = "Cambridge Network",
	CENTER_CARE = "Center Care",
	CHP_STUDENT_HEALTH = "CHP Student Health",
	CIGNA = "CIGNA",
	CIGNA_PLAN_NATIONAL_NALC = "Cigna Plan National NALC",
	CIGNA_COLUMBIA_EMPLOYEE_POS = "cigna-columbia Employee Pos",
	COMMUNITY_CARE_NETWORK = "Community Care Network",
	COMMUNITY_PREMIER_PLUS = "Community Premier Plus",
	CONNECTICARE = "Connecticare",
	CONNECTICARE_FLEX = "Connecticare FLEX",
	CONSOLIDATED_SERVICES_GROUP = "CONSOLIDATED SERVICES GROUP",
	CONSUMER_HEALTH_NETWORK = "Consumer Health Network",
	COVENTRY_HEALTHCARE = "Coventry Healthcare",
	DEVON_HEALTH_SERVICES = "Devon Health Services",
	DEVON_HEALTH_SERVICES_ULLICARE = "Devon Health Services Ullicare",
	ELDERPLAN_FIDA = "Elderplan FIDA",
	EMBLEM_HEALTH_GHI = "Emblem Health GHI",
	EMBLEM_HIP_ESSENTIAL = "Emblem HIP Essential",
	EMBLEM_SELECT_CARE = "Emblem Select Care",
	EMBLEMHEALTH_GHI = "EmblemHealth GHI",
	EMBLEMHEALTH_HIP = "EmblemHealth HIP",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_BLUE_PRIORITY = "Empire Blue Cross Blue Shield Blue Priority",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_CHILD_HEALTH_PLUS = "Empire Blue Cross Blue Shield Child Health Plus",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_HEALTH_CHOICE = "Empire Blue Cross Blue Shield Health Choice",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_HEALTHPLUS_ESSENTIAL = "Empire Blue Cross Blue Shield Healthplus Essential",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_LOCAL_32BJ = "Empire Blue Cross Blue Shield Local 32BJ",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_MEDIBLUE = "Empire Blue Cross Blue Shield Mediblue",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_MEDIBLUE_SENIOR = "Empire Blue Cross Blue Shield Mediblue Senior",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_NYP = "Empire Blue Cross Blue Shield NYP",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_PATHWAY_X = "Empire Blue Cross Blue Shield Pathway X",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_PATHWAY_X_ENHANCED = "Empire Blue Cross Blue Shield Pathway X Enhanced",
	EVERCARE_PLAN_DH = "Evercare Plan DH",
	FIDELIS_BETTER_HEALTH_PLAN = "Fidelis BETTER HEALTH PLAN",
	FIDELIS_CARE = "Fidelis Care",
	FIDELIS_CHILD_FAMILY_HEALTH_PLUS = "Fidelis Child Family Health Plus",
	FIRST_HEALTH = "First Health",
	FIRST_HEALTH_AFFORDABLE = "First Health Affordable",
	GALAXY_HEALTH_NETWORK = "Galaxy Health Network",
	GHI_PREMIER = "GHI Premier",
	GREAT_WEST_NATIONAL = "Great West National",
	GROUP_HEALTH_INCORPORATED = "Group Health Incorporated",
	GUARDIAN_LIFE = "Guardian Life",
	HEALTH_FIRST = "Health First",
	HEALTH_FIRST_CHILD_HEALTH_PLUS = "Health First Child Health Plus",
	HEALTH_INSURANCE_PLAN_INSURANCE_PLAN_NEW_YORK_SELECT_CARE = "Health Insurance Plan Insurance Plan New York Select Care",
	HEALTH_INSURANCE_PLAN_OF_NEW_YORK_HIP = "Health Insurance Plan Of New York HIP",
	HEALTH_NET = "Health Net",
	HEALTH_PLAN_OF_NEVADA_NATIONAL = "Health Plan Of Nevada National",
	HEALTH_PLUS_AMERIGROUP = "Health Plus Amerigroup",
	HEALTHCARE_PARTNERS = "Healthcare Partners",
	HEALTHFIRST = "Healthfirst",
	HEALTHPARTNERS_OPEN_ACCESS = "HEALTHPARTNERS OPEN ACCESS",
	HEALTHSOUTH = "HealthSouth",
	HERITAGE = "Heritage",
	HIP_INSURANCE_PLAN_OF_NEW_YORK_VYTRA = "HIP Insurance Plan Of New York Vytra",
	HORIZON_BLUE_CROSS_BLUE_SHIELD = "Horizon Blue Cross Blue Shield",
	HORIZON_BLUE_CROSS_BLUE_SHIELD_OF_NEW_JERSEY = "Horizon Blue Cross Blue Shield of New Jersey",
	HORIZON_HEALTHCARE_OF_NEW_YORK = "Horizon Healthcare of New York",
	HUMAN_CHOICE_CARE = "Human Choice Care",
	HUMANA = "Humana",
	INDEPENDENT_HEALTH_ASSOCIATION = "Independent Health Association",
	LOCAL_32BJ_HEALTH_FUND = "Local 32BJ Health Fund",
	MAGNA_HEALTH = "Magna Health",
	MAGNA_PREFERRED_MAGNA_CARE = "Magna Preferred Magna Care",
	MAGNACARE_NATIONAL = "Magnacare national",
	MANAGED_HEALTH_CARE_ALLIANCE___QUALCOMM = "Managed Health Care Alliance - Qualcomm",
	MEDICA_CHOICE_NATIONAL = "Medica Choice National",
	MEDICAID = "Medicaid",
	MEDICARE = "Medicare",
	METLIFE = "MetLife",
	MULTIPLAN = "Multiplan",
	MVP_CIGNA_HEALTH_PLAN_NATIONAL = "MVP Cigna Health Plan National",
	MVP_CIGNA_HEALTH_PLAN_OPEN_ACCESS = "MVP Cigna Health Plan Open Access",
	MVP_HEALTH_CARE = "MVP Health Care",
	NATIONAL_HEALTH_ADMINISTRATORS = "National Health Administrators",
	NATIONAL_PREFERRED_PROVIDER_NETWORK = "National Preferred Provider Network",
	NEIGHBORHOOD_HEALTH_PROVIDERS = "Neighborhood Health Providers",
	NEW_JERSEY_MEDICAID = "New Jersey Medicaid",
	NEW_YORK_HOSPITAL_COMMUNITY_HEALTH = "New York Hospital Community Health",
	NYP_SYSTEM_SELECTHEALTH = "NYP System Selecthealth",
	NYP_SYSTEM_SELECT_HEALTH = "NYP-SYSTEM SELECT HEALTH",
	ONE_HEALTH_PLAN = "One Health Plan",
	OSCAR = "Oscar",
	OXFORD_COMMUNITY = "Oxford Community",
	OXFORD_FREEDOM = "Oxford Freedom",
	OXFORD_HEALTH_PLANS = "Oxford Health Plans",
	OXFORD_LIBERTY = "Oxford Liberty",
	OXFORD_MEDICARE = "Oxford Medicare",
	OXFORD_MEDICARE_ADVANTAGE = "Oxford Medicare Advantage",
	OXFORD_METRO_CORE_CHARTER = "Oxford Metro Core Charter",
	PACIFICARE_NATIONAL = "Pacificare National",
	PHYSICIANS_HEALTH_SERVICES = "Physicians Health Services",
	POMCO = "POMCO",
	POMCO_WITH_MULTIPLAN_ALLIED_NATIONAL = "POMCO with Multiplan Allied National",
	PRIVATE_HEALTHCARE_SYSTEMS = "Private Healthcare Systems",
	PRUDENTIAL = "Prudential",
	QUALCARE = "Qualcare",
	RAILROAD = "Railroad",
	ROCKEFELLER_UNIVERSITY = "Rockefeller University",
	ROCKEFELLER_UNIVERSITY___CORESOURCE = "Rockefeller University - CoreSource",
	SECURE_HORIZONS = "Secure Horizons",
	SELECT_HEALTH_NATIONAL = "Select Health National",
	SELECTPRO = "SelectPro",
	THREE_RIVERS_PROVIDER_NETWORK = "Three Rivers Provider Network",
	TRICARE = "TRICARE",
	UNICARE = "Unicare",
	UNITED_EMPIRE = "United Empire",
	UNITED_HEALTH_CARE_AMERICHOICE = "United Health Care Americhoice",
	UNITED_HEALTH_CARE_COMPASS = "United Health Care Compass",
	UNITED_HEALTH_CARE_LIBERTY = "United Health Care Liberty",
	UNITED_HEALTHCARE_COLUMBIA = "United Healthcare Columbia",
	UNITED_HEALTHCARE_COMMUNITY_PLAN = "United Healthcare Community Plan",
	UNITED_HEALTHCARE_ESSENTIAL = "United Healthcare Essential",
	UNITED_PAYORS_AND_UNITED_PROVIDERS = "United Payors and United Providers",
	UNITEDHEALTHCARE = "UnitedHealthcare",
	UNITEDHEALTHCARE_AMERICHOICE = "UnitedHealthcare AMERICHOICE",
	UNITEDHEALTHCARE_COLUMBIA = "UnitedHealthcare COLUMBIA",
	UNITEDHEALTHCARE_COMMUNITY_PLAN = "UnitedHealthcare COMMUNITY PLAN",
	UNITY_HEALTH_PLAN_NATIONAL = "Unity Health Plan National",
	VNSNY_CHOICE = "VNSNY CHOICE",
	WEILL_CORNELL_AETNA = "Weill Cornell Aetna",
	WELLCARE = "WellCare",
	WELLCHOICE = "WellChoice",
	WORKERS__COMPENSATION = "Workers' Compensation",
	AGEWELL_MEDICARE = "Agewell Medicare",
	AMERIGROUP_NJ = "Amerigroup NJ",
	ANTHEM = "Anthem",
	ANTHEM_HMO__PPO__INDEMNITY = "Anthem HMO, PPO, Indemnity",
	AMIDA_CARE_MEDICAID__HARP = "Amida Care  Medicaid, HARP",
	ARCHCARE_ADVANTAGE_HMO = "ArchCare Advantage HMO",
	ELDERPLAN = "Elderplan",
	CENTERLIGHT = "Centerlight",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_HEALTHPLUS_CHP = "Empire Blue Cross Blue Shield Healthplus CHP",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_HEALTHPLUS_MEDICAID = "Empire Blue Cross Blue Shield Healthplus Medicaid",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_HEALTHPLUS_MEDICAID__HARP = "Empire Blue Cross Blue Shield Healthplus Medicaid; HARP",
	HEALTHFIRST_CHILD_HEALTH_PLUS = "Healthfirst Child Health Plus",
	HEALTHFIRST_ESSENTIAL_1_4 = "Healthfirst Essential 1-4",
	HEALTHCARE_PARTNERS_COMMERCIAL__MEDICAID__MEDICARE = "Healthcare Partners Commercial, Medicaid, Medicare",
	FIDALIS = "Fidalis",
	HEALTHFIRST_EXCHANGE = "Healthfirst Exchange",
	HEALTHFIRST_MEDICAID__HARP = "Healthfirst Medicaid, HARP",
	HEALTHFIRST_MEDICARE = "Healthfirst Medicare",
	MAGNACARE_COMMERCIAL = "Magnacare Commercial",
	OXFORD = "Oxford",
	OXFORD_FREEDOM__GARDEN_STATE = "Oxford Freedom/ Garden State",
	OXFORD_METRO = "Oxford Metro",
	OXFORD_MOSAIC = "Oxford Mosaic",
	PACIFICARE_PPO = "Pacificare PPO",
	THE_EMPIRE_PLAN = "The Empire Plan",
	TRICARE_HMO__POS__EPO__PPO = "TRICARE HMO, POS, EPO, PPO",
	UNITED_BEHAVIORAL_HEALTH_COMMERCIAL__MEDICAID__HARP__MEDICARE = "United Behavioral Health Commercial; Medicaid; HARP; Medicare",
	UNITED_HEALTH_CARE = "United Health Care",
	VNSNY_CHOICE_MEDICAID__HARP = "VNSNY CHOICE Medicaid, HARP",
	VNSNY_CHOICE_MEDICARE = "VNSNY CHOICE Medicare",
	VYTRA_HEALTHCARE_HMO__PPO = "Vytra Healthcare HMO, PPO",
	WELLCARE_CHP = "WellCare  CHP",
	WELLCARE_AMERICAN_PROGRESSIVE_LIFE = "WellCare American Progressive Life",
	WELLCARE_MEDICAID__HARP = "WellCare Medicaid, HARP",
	WELLCARE_MEDICARE = "WellCare Medicare",
	WELLCARE_MTLC = "WellCare MTLC",
	EMBLEM_HIP = "Emblem/Hip",
	LOCAL_1199 = "Local 1199",
	MAGNACARE = "Magnacare",
	EMBLEM_GHI = "Emblem/GHI",
	AGEWELL = "AgeWell",
	CAPITAL_DISTRICT_PHYSICIAN_HEALTH_PLAN = "Capital District Physician Health Plan",
	GHI = "GHI",
	AFFINITY__HMO_ = "Affinity [HMO]",
	AETNA__WEILL_CORNELL_EMPLOYEE_PLAN_ = "Aetna [Weill Cornell Employee Plan]",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD__PATHWAY_ENHANCED_ = "Empire Blue Cross Blue Shield [Pathway Enhanced]",
	OSCAR__EXCHANGE_ = "Oscar (Exchange)",
	OXFORD_HEALTH_PLANS__METRO_CORE_CHARTER__HMO__ = "Oxford Health Plans [Metro/Core/Charter (HMO)]",
	HEALTH_NET__PHS_ = "Health Net (PHS)",
	MVP_CIGNA_HEALTH_PLAN = "MVP Cigna Health Plan",
	PRIVATE_HEALTHCARE_SYSTEMS__PHCS_ = "Private Healthcare Systems (PHCS)",
	AETNA_WEILL_CORNELL_MEDICINE__PPO_CORNELL_UNIVERSITY_ = "Aetna Weill Cornell Medicine [PPO Cornell University]",
	QUALITY_HEALTH_MANAGEMENT = "Quality Health Management",
	COVENTRY_HEALTH_CARE = "Coventry Health Care",
	_GENERAL_ = "(General)",
	GHI_EMBLEM_HEALTH = "GHI Emblem Health",
	EMBLEM_SELECT_CARE__EXCHANGE_ = "Emblem Select Care [Exchange]",
	BEECHSTREET__MEDICHOICE_ = "Beechstreet (Medichoice)",
	HORIZON_BC_BS_OF_NEW_JERSEY__PPO_ = "Horizon BC/BS of New Jersey [PPO]",
	UNITED_PAYORS___UNITED_PROVIDERS = "United Payors & United Providers",
	GREAT_WEST = "Great West",
	DENTAQUEST = "DentaQuest",
	UNITEDHEALTHCARE__THE_EMPIRE_PLAN_ = "UnitedHealthcare [The Empire Plan]",
	PRIVATE_HEALTHCARE_SYSTEMS__PHCS_NATIONAL_ = "Private Healthcare Systems (PHCS/National)",
	COVENTRY_HEALTHCARE__NATIONAL_ = "Coventry Healthcare (National)",
	DEVON_HEALTH_SERVICES__ULLICARE_ = "Devon Health Services (Ullicare)",
	MANAGED_HEALTH_CARE_ALLIANCE__QUALC = "Managed Health Care Alliance/ QUALC",
	CONSUMER_HEALTH_NETWORK__CHN_ = "Consumer Health Network (CHN)",
	VYTRA__EPO_ = "VYTRA [EPO]",
	POMCO_W__MULTIPLAN_ALLIED__NATIONAL_ = "POMCO w/ Multiplan Allied (National)",
	FIRST_HEALTH__NATIONAL_ = "First Health (National)",
	BETTER_HEALTH_PLAN_FIDELIS = "BETTER HEALTH PLAN/FIDELIS",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD__INDEMNITY_ = "Empire Blue Cross Blue Shield [Indemnity]",
	BLUE_SHIELD = "Blue Shield",
	CHN_CONSOLIDATED_SERVICES_GROUP = "CHN-CONSOLIDATED SERVICES GROUP",
	NALC_CIGNA_PLAN__NATIONAL_ = "NALC Cigna Plan (National)",
	MVP_CIGNA_HEALTH_PLAN__NATIONAL_ = "MVP Cigna Health Plan (National)",
	UNITY_HEALTH_PLAN__NATIONAL_ = "Unity Health Plan (National)",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD = "Empire Blue Cross/Blue Shield",
	HEALTH_INSURANCE_PLAN_OF_NY__HIP_ = "Health Insurance Plan of NY (HIP)",
	VNSNY_CHOICE_SELECTHEALTH = "VNSNY CHOICE SelectHealth",
	MAGNACARE__NATIONAL_ = "Magnacare (National)",
	HEALTH_PLUS___AMERIGROUP = "Health Plus - Amerigroup",
	HORIZON_TRADITIONAL = "Horizon Traditional",
	WORKERS_COMPENSATION = "Workers Compensation",
	UNITED_HEALTHCARE = "United Healthcare",
	AETNA___NYP = "Aetna - NYP",
	AETNA___WEILL_CORNELL = "Aetna - Weill Cornell",
	EMPIRE_BLUE_CROSS_BLUE_SHIELD_HEALTHPLUS = "Empire Blue Cross/Blue Shield Healthplus",
	RIVERSPRING = "RiverSpring",
	CAPITAL_DISTRICT_PHYSICIAN_HEALTH_PLAN__CDPHP_ = "Capital District Physician Health Plan (CDPHP)",
	AMERIHEALTH_OF_NEW_JERSEY = "AmeriHealth of New Jersey",
	AMERIGROUP_OF_NEW_JERSEY = "Amerigroup of New Jersey",
	HEALTHPLEX = "Healthplex",
	GUARDIAN = "Guardian",
	MARCH_VISION = "March Vision",
	COLORADO_MEDICAID = "Colorado Medicaid",
	AETNA___WEILL_CORNELL_MEDICINE = "Aetna - Weill Cornell Medicine",
}

export enum C_languagesFilter {
	CHINESE = "Chinese",
	MANDARIN = "Mandarin",
	HINDI = "Hindi",
	GUJARATI = "Gujarati",
	SPANISH = "Spanish",
	FRENCH = "French",
	FINNISH = "Finnish",
	ITALIAN = "Italian",
	KOREAN = "Korean",
	YIDDISH = "Yiddish",
	HEBREW = "Hebrew",
	BENGALI = "Bengali",
	RUSSIAN = "Russian",
	ARABIC = "Arabic",
	HUNGARIAN = "Hungarian",
	PORTUGUESE = "Portuguese",
	GERMAN = "German",
	ROMANIAN = "Romanian",
	DUTCH = "Dutch",
	URDU = "Urdu",
	MARATHI = "Marathi",
	PUNJABI = "Punjabi",
	GREEK = "Greek",
	UKRAINIAN = "Ukrainian",
	CANTONESE = "Cantonese",
	CROATIAN = "Croatian",
	TURKISH = "Turkish",
	FARSI = "Farsi",
	TELUGU = "Telugu",
	JAPANESE = "Japanese",
	THAI = "Thai",
	POLISH = "Polish",
	TAIWANESE = "Taiwanese",
	TAGALOG = "Tagalog",
	SIGN_LANGUAGE = "Sign Language",
	TAMIL = "Tamil",
	SLOVENIAN = "Slovenian",
	MALAYALAM = "Malayalam",
	SERBIAN = "Serbian",
	SWEDISH = "Swedish",
	ARMENIAN = "Armenian",
	SINDHI = "Sindhi",
	ENGLISH = "English",
	VIETNAMESE = "Vietnamese",
	MALAY = "Malay",
	BULGARIAN = "Bulgarian",
	ASSYRIAN = "Assyrian",
	FILIPINO = "Filipino",
	YORUBA = "Yoruba",
	AMHARIC = "Amharic",
	BOSNIAN = "Bosnian",
	TWI = "Twi",
	PERSIAN = "Persian",
	CZECH = "Czech",
}

export interface C_nYPMGSpecificOpenSchedulingOptions {
	name?: string,
	iD?: string,
}

export interface C_openSchedulingOptions {
	name?: string,
	iD?: string,
}

export enum C_primarySpecialties {
	CLINICAL_MOLECULAR_GENETICS_AND_GENOMICS = "Clinical Molecular Genetics and Genomics",
	PHYSICAL_MEDICINE_AND_REHABILITATION = "Physical Medicine and Rehabilitation",
	NEONATAL_PERINATAL_MEDICINE = "Neonatal-Perinatal Medicine",
	OPTOMETRY = "Optometry",
	INTERVENTIONAL_RADIOLOGY = "Interventional Radiology",
	FORENSIC_PSYCHIATRY = "Forensic Psychiatry",
	PEDIATRIC_RADIOLOGY = "Pediatric Radiology",
	OBSTETRICAL_ANESTHESIA = "Obstetrical Anesthesia",
	PEDIATRIC_NEUROLOGY = "Pediatric Neurology",
	PEDIATRIC_ALLERGY___IMMUNOLOGY = "Pediatric Allergy & Immunology",
	ADULT_CONGENITAL_HEART_DISEASE = "Adult Congenital Heart Disease",
	INFECTIOUS_DISEASE = "Infectious Disease",
	CARDIOLOGY = "Cardiology",
	ADDICTION_PSYCHIATRY = "Addiction Psychiatry",
	TRANSPLANT_NEPHROLOGY = "Transplant Nephrology",
	CONGENITAL_CARDIAC_SURGERY = "Congenital Cardiac Surgery",
	RENAL_PATHOLOGY = "Renal Pathology",
	MATERNAL_AND_FETAL_MEDICINE = "Maternal and Fetal Medicine",
	HAND_SURGERY = "Hand Surgery",
	PEDIATRIC_ORTHOPEDICS = "Pediatric Orthopedics",
	NEPHROLOGY = "Nephrology",
	ENDOCRINOLOGY = "Endocrinology",
	NEUROPSYCHOLOGY = "Neuropsychology",
	ADVANCED_HEART_FAILURE_AND_TRANSPLANT_CARDIOLOGY = "Advanced Heart Failure and Transplant Cardiology",
	CARDIOTHORACIC_SURGERY = "Cardiothoracic Surgery",
	SPINAL_CORD_INJURY_MEDICINE = "Spinal Cord Injury Medicine",
	FAMILY_PSYCHOTHERAPY = "Family Psychotherapy",
	BARIATRIC_SURGERY = "Bariatric Surgery",
	CHILD_NEUROLOGY = "Child Neurology",
	ORAL_AND_MAXILLOFACIAL_RADIOLOGY = "Oral and Maxillofacial Radiology",
	ADOLESCENT_PSYCHOLOGY = "Adolescent Psychology",
	HEPATOBILIARY_SURGERY = "Hepatobiliary Surgery",
	GASTROINTESTINAL_PATHOLOGY = "Gastrointestinal Pathology",
	HOSPICE_AND_PALLIATIVE_MEDICINE = "Hospice and Palliative Medicine",
	PERIODONTICS = "Periodontics",
	AUTISTIC_SPECTRUM_DISORDERS = "Autistic Spectrum Disorders",
	ORTHOPAEDIC_SPORTS_MEDICINE = "Orthopaedic Sports Medicine",
	ATTENTION_DEF_HYPERACTIVE__ADHD_ = "Attention Def Hyperactive (ADHD)",
	PSYCHOLOGY = "Psychology",
	VASCULAR_SURGERY = "Vascular Surgery",
	TRAUMA_SURGERY = "Trauma Surgery",
	PEDIATRIC_NEPHROLOGY = "Pediatric Nephrology",
	RETINAL_DISORDER = "Retinal Disorder",
	CONSULT_PSYCHIATRY = "Consult Psychiatry",
	ANESTHESIOLOGY_CRITICAL_CARE_MEDICINE = "Anesthesiology Critical Care Medicine",
	PEDIATRIC_ALLERGY_AND_IMMUNOLOGY = "Pediatric Allergy and Immunology",
	HEAD___NECK_SURGERY = "Head & Neck Surgery",
	FAMILY_MEDICINE = "Family Medicine",
	PEDIATRIC_NEUROLOGICAL_SURGERY = "Pediatric Neurological Surgery",
	WOUND_CARE = "Wound Care",
	TRANSPLANT_SURGERY = "Transplant Surgery",
	NEUROPATHOLOGY = "Neuropathology",
	RHINOLOGY = "Rhinology",
	EXECUTIVE_HEALTH = "Executive Health",
	NEURODEVELOPMENTAL_DISABILITIES = "Neurodevelopmental Disabilities",
	SLEEP_MEDICINE = "Sleep Medicine",
	RADIOLOGY = "Radiology",
	HEMATOLOGY_AND_ONCOLOGY = "Hematology and Oncology",
	PEDIATRIC_SLEEP_MEDICINE = "Pediatric Sleep Medicine",
	PEDIATRIC_UROLOGY = "Pediatric Urology",
	PEDIATRIC_THORACIC_SURGERY = "Pediatric Thoracic Surgery",
	ADOLESCENT_MEDICINE = "Adolescent Medicine",
	SURGICAL_CRITICAL_CARE = "Surgical Critical Care",
	NEURO_OPHTHALMOLOGY = "Neuro-Ophthalmology",
	PULMONARY_MEDICINE = "Pulmonary Medicine",
	IMMUNOPATHOLOGY = "Immunopathology",
	ANATOMIC_PATHOLOGY = "Anatomic Pathology",
	PLASTIC_SURGERY_WITHIN_THE_HEAD_AND_NECK = "Plastic Surgery Within the Head and Neck",
	MEDICAL_MICROBIOLOGY = "Medical Microbiology",
	GERIATRIC_PSYCHIATRY = "Geriatric Psychiatry",
	DENTISTRY = "Dentistry",
	ENDOCRINE_SURGERY = "Endocrine Surgery",
	PERIODONTOLOGY = "Periodontology",
	ORTHOPEDIC_SPORTS_MEDICINE = "Orthopedic Sports Medicine",
	PAIN_MEDICINE = "Pain Medicine",
	GENERAL_OPHTHALMOLOGY = "General Ophthalmology",
	NUCLEAR_CARDIOLOGY = "Nuclear Cardiology",
	DEVELOPMENTAL_BEHAVIORAL_PEDIATRICS = "Developmental-Behavioral Pediatrics",
	PODIATRY = "Podiatry",
	PEDIATRIC_HEMATOLOGY_ONCOLOGY = "Pediatric Hematology-Oncology",
	PEDIATRIC_GASTROENTEROLOGY = "Pediatric Gastroenterology",
	PROSTHODONTICS = "Prosthodontics",
	CRITICAL_CARE_MEDICINE = "Critical Care Medicine",
	NEONATOLOGY = "Neonatology",
	CLINICAL_CYTOGENETICS_AND_GENOMICS = "Clinical Cytogenetics and Genomics",
	PEDIATRIC_REHABILITATION_MEDICINE = "Pediatric Rehabilitation Medicine",
	SPINAL_SURGERY = "Spinal Surgery",
	CERTIFIED_NURSE_MIDWIFE = "Certified Nurse Midwife",
	VASCULAR_NEUROLOGY = "Vascular Neurology",
	HEMATOLOGY_PATHOLOGY = "Hematology Pathology",
	FACIAL_PLASTIC_AND_RECONSTRUCTIVE_SURGERY = "Facial Plastic and Reconstructive Surgery",
	OBSTETRICS_AND_GYNECOLOGY__OBGYN_ = "Obstetrics and Gynecology (OBGYN)",
	ENDODONTICS = "Endodontics",
	ADULT_ADHD = "Adult ADHD",
	OBESITY_MEDICINE = "Obesity Medicine",
	PEDIATRICS = "Pediatrics",
	OTOLARYNGOLOGY = "Otolaryngology",
	RADIATION_ONCOLOGY = "Radiation Oncology",
	ELECTRODIAGNOSTIC_MEDICINE = "Electrodiagnostic Medicine",
	NEURO_OTOLOGY = "Neuro Otology",
	REPRODUCTIVE_ENDOCRINOLOGY = "Reproductive Endocrinology",
	ORAL_AND_MAXILLOFACIAL_SURGERY = "Oral and Maxillofacial Surgery",
	LUPUS = "Lupus",
	ALLERGY_AND_IMMUNOLOGY = "Allergy and Immunology",
	CYTOPATHOLOGY = "Cytopathology",
	FOOT_AND_ANKLE_CARE = "Foot and Ankle Care",
	PEDIATRIC_ONCOLOGY = "Pediatric Oncology",
	HEMATOLOGY_ONCOLOGY = "Hematology-Oncology",
	CLINICAL_CARDIAC_ELECTROPHYSIOLOGY = "Clinical Cardiac Electrophysiology",
	HEPATOLOGY = "Hepatology",
	PEDIATRIC_TRANSPLANT_HEPATOLOGY = "Pediatric Transplant Hepatology",
	ORTHODONTICS = "Orthodontics",
	PEDIATRIC_CARDIAC_SURGERY = "Pediatric Cardiac Surgery",
	NEUROLOGY = "Neurology",
	CARDIAC_SURGERY = "Cardiac Surgery",
	OPHTHALMOLOGY = "Ophthalmology",
	PLASTIC_AND_RECONSTRUCTIVE_SURGERY = "Plastic and Reconstructive Surgery",
	PEDIATRIC_OTOLARYNGOLOGY = "Pediatric Otolaryngology",
	UROLOGY = "Urology",
	ORAL_AND_MAXILLOFACIAL_PATHOLOGY = "Oral and Maxillofacial Pathology",
	NEURO_ONCOLOGY = "Neuro-Oncology",
	PSYCHIATRIC_CONSULTATION = "Psychiatric Consultation",
	NEUROENDOCRINOLOGY = "Neuroendocrinology",
	PEDIATRIC_NEUROSURGERY = "Pediatric Neurosurgery",
	LIVER_CANCER = "Liver Cancer",
	GERIATRIC_MEDICINE = "Geriatric Medicine",
	CANCER_CARE = "Cancer Care",
	CLINICAL_INFORMATICS = "Clinical Informatics",
	INTERVENTIONAL_NEURORADIOLOGY = "Interventional Neuroradiology",
	CRITICAL_CARE_NEUROLOGY = "Critical Care Neurology",
	OCCUPATIONAL_MEDICINE = "Occupational Medicine",
	GENDER_DYSPHORIA = "Gender Dysphoria",
	PEDIATRIC_CARDIOLOGY = "Pediatric Cardiology",
	RADIOLOGY__VASCULAR_INTERVENTIONAL = "Radiology, Vascular/Interventional",
	INTERVENTIONAL_SPINE_CARE = "Interventional Spine Care",
	VASCULAR_AND_INTERVENTIONAL_RADIOLOGY = "Vascular and Interventional Radiology",
	PEDIATRIC_ANESTHESIA = "Pediatric Anesthesia",
	PEDIATRIC_CRITICAL_CARE = "Pediatric Critical Care",
	PULMONARY_DISEASE_MEDICINE = "Pulmonary Disease Medicine",
	EPILEPSY = "Epilepsy",
	DERMATOPATHOLOGY = "Dermatopathology",
	FOOT_AND_ANKLE_SURGERY = "Foot and Ankle Surgery",
	PEDIATRIC_OPHTHALMOLOGY = "Pediatric Ophthalmology",
	RHEUMATOID_ARTHRITIS = "Rheumatoid Arthritis",
	INTERVENTIONAL_CARDIOLOGY = "Interventional Cardiology",
	MEDICAL_ONCOLOGY = "Medical Oncology",
	CARDIOVASCULAR_DISEASE = "Cardiovascular Disease",
	PUBLIC_HEALTH_AND_GENERAL_PREVENTIVE_MEDICINE = "Public Health and General Preventive Medicine",
	PEDIATRIC_CRITICAL_CARE_MEDICINE = "Pediatric Critical Care Medicine",
	PEDIATRIC_PATHOLOGY = "Pediatric Pathology",
	CHILD_AND_ADOLESCENT_PSYCHOLOGY = "Child and Adolescent Psychology",
	COUPLES_THERAPY = "Couples Therapy",
	EMERGENCY_MEDICINE = "Emergency Medicine",
	CHILD_AND_ADOLESCENT_PSYCHIATRY = "Child and Adolescent Psychiatry",
	NEURODEVELOPMENTAL_DISORDERS = "Neurodevelopmental Disorders",
	CLINICAL_NEUROPSYCHOLOGY = "Clinical Neuropsychology",
	LGBT_MENTAL_HEALTH = "LGBT Mental Health",
	MEDICAL_PHYSICS = "Medical Physics",
	INTERNAL_MEDICINE = "Internal Medicine",
	NEUROMUSCULAR_MEDICINE = "Neuromuscular Medicine",
	OPHTHALMIC_PLASTIC_AND_RECONSTRUCTIVE_SURGERY = "Ophthalmic Plastic and Reconstructive Surgery",
	GYNECOLOGIC_ONCOLOGY = "Gynecologic Oncology",
	COLON_AND_RECTAL_SURGERY = "Colon and Rectal Surgery",
	PEDIATRIC_ENDOCRINOLOGY = "Pediatric Endocrinology",
	THORACIC_AND_CARDIAC_SURGERY = "Thoracic and Cardiac Surgery",
	NEUROTOLOGY = "Neurotology",
	PEDIATRIC_DENTISTRY = "Pediatric Dentistry",
	NEUROLOGICAL_SURGERY = "Neurological Surgery",
	GASTROENTEROLOGY = "Gastroenterology",
	HEAD_AND_NECK_SURGERY = "Head and Neck Surgery",
	SURGICAL_ONCOLOGY = "Surgical Oncology",
	GENERAL_SURGERY = "General Surgery",
	CLINICAL_PATHOLOGY = "Clinical Pathology",
	PEDIATRIC_ORTHOPEDIC_SURGERY = "Pediatric Orthopedic Surgery",
	UROLOGIC_SURGERY = "Urologic Surgery",
	PSYCHIATRY = "Psychiatry",
	UROGYNECOLOGY = "Urogynecology",
	MOLECULAR_GENETIC_PATHOLOGY = "Molecular Genetic Pathology",
	PEDIATRIC_BEHAVIOR_AND_DEVELOPMENT = "Pediatric Behavior and Development",
	ANESTHESIOLOGY = "Anesthesiology",
	ORTHOPEDIC_SURGERY = "Orthopedic Surgery",
	PEDIATRIC_ANESTHESIOLOGY = "Pediatric Anesthesiology",
	PATHOLOGY = "Pathology",
	DIAGNOSTIC_RADIOLOGY = "Diagnostic Radiology",
	DERMATOLOGY = "Dermatology",
	NEURORADIOLOGY = "Neuroradiology",
	BLOOD_BANKING_TRANSFUSION_MEDICINE = "Blood Banking/Transfusion Medicine",
	CLINICAL_BIOCHEMICAL_GENETICS = "Clinical Biochemical Genetics",
	CHILD_AND_ADOLESCENT_PSYCHOPHARMACOLOGY = "Child and Adolescent Psychopharmacology",
	COMPLEX_GENERAL_SURGICAL_ONCOLOGY = "Complex General Surgical Oncology",
	PEDIATRIC_SURGERY = "Pediatric Surgery",
	NUCLEAR_MEDICINE = "Nuclear Medicine",
	PAIN_MEDICINE_PAIN_MANAGEMENT = "Pain Medicine/Pain Management",
	CLINICAL_GENETICS_AND_GENOMICS__MD_ = "Clinical Genetics and Genomics (MD)",
	PEDIATRIC_EMERGENCY_MEDICINE = "Pediatric Emergency Medicine",
	PEDIATRIC_CARDIOTHORACIC_SURGERY = "Pediatric Cardiothoracic Surgery",
	ANATOMIC_PATHOLOGY_AND_CLINICAL_PATHOLOGY = "Anatomic Pathology and Clinical Pathology",
	INTERVENTIONAL_RADIOLOGY_AND_DIAGNOSTIC_RADIOLOGY = "Interventional Radiology and Diagnostic Radiology",
	PREVENTIVE_MEDICINE = "Preventive Medicine",
	ORTHOGNATHIC_SURGERY = "Orthognathic Surgery",
	PSYCHOSOMATIC_MEDICINE = "Psychosomatic Medicine",
	SURGERY = "Surgery",
	BREAST_SURGERY = "Breast Surgery",
	NEURO_RADIOLOGY = "Neuro Radiology",
	DIABETES_MEDICINE = "Diabetes Medicine",
	TRANSPLANT_HEPATOLOGY = "Transplant Hepatology",
	LABORATORY_MEDICINE = "Laboratory Medicine",
	RHEUMATOLOGY = "Rheumatology",
	PEDIATRIC_PULMONOLOGY = "Pediatric Pulmonology",
	FEMALE_PELVIC_MEDICINE_AND_RECONSTRUCTIVE_SURGERY = "Female Pelvic Medicine and Reconstructive Surgery",
	HEMATOLOGY = "Hematology",
	PEDIATRIC_INFECTIOUS_DISEASES = "Pediatric Infectious Diseases",
	PEDIATRIC_RHEUMATOLOGY = "Pediatric Rheumatology",
	CLINICAL_NEUROPHYSIOLOGY = "Clinical Neurophysiology",
	SPORTS_MEDICINE = "Sports Medicine",
	PEDIATRIC_DERMATOLOGY = "Pediatric Dermatology",
	SURGERY_OF_THE_HAND = "Surgery of the Hand",
	GYNECOLOGICAL_ONCOLOGY = "Gynecological Oncology",
	PATHOLOGY___MOLECULAR_GENETIC = "Pathology - Molecular Genetic",
	SURGERY__THORACIC_CARDIOVASCULAR = "Surgery, Thoracic Cardiovascular",
	MINIMALLY_INVASIVE_GYNECOLOGIC_SURGERY = "Minimally Invasive Gynecologic Surgery",
	SURGERY__GENERAL = "Surgery, General",
	ENDOCRINOLOGY__DIABETES_AND_METABOLISM = "Endocrinology, Diabetes and Metabolism",
	SURGERY__ORAL_AND_MAXILLOFACIAL = "Surgery, Oral and Maxillofacial",
	REPRODUCTIVE_ENDOCRINOLOGY_INFERTILITY = "Reproductive Endocrinology/Infertility",
	GYNECOLOGY = "Gynecology",
	ACUPUNCTURIST = "Acupuncturist",
	ORAL_AND_MAXILLOFACIAL = "Oral and Maxillofacial",
	DIABETES_AND_METABOLISM = "Diabetes and Metabolism",
	TRANSPLANT_PULMONOLOGY = "Transplant Pulmonology",
	PEDIATRICIAN__GENERAL_PEDIATRICS_ = "Pediatrician (General Pediatrics)",
	SHOULDER__ELBOW___SPORTS_MEDICINE = "Shoulder, Elbow & Sports Medicine",
	HIP___KNEE_RECONSTRUCTION = "Hip & Knee Reconstruction",
	NEUROLOGIST = "Neurologist",
	NEUROSURGERY = "Neurosurgery",
	NEUROSURGEON = "Neurosurgeon",
	CERTIFIED_MIDWIFE = "Certified Midwife",
}

export enum C_primarySpecialtyPhynd {
	NEUROPSYCHOLOGY = "Neuropsychology",
	CARDIOLOGY = "Cardiology",
	KIDNEY_TRANSPLANT_SURGERY = "Kidney Transplant Surgery",
	PANCREAS___HEPATOBILIARY_SURGERY = "Pancreas & Hepatobiliary Surgery",
	BLOOD_BANKING_TRANSFUSION_MEDICINE = "Blood Banking/Transfusion Medicine",
	PATHOLOGY___CLINICAL = "Pathology - Clinical",
	OBSTETRICS_AND_GYNECOLOGY = "Obstetrics and Gynecology",
	INTERNAL_MEDICINE = "Internal Medicine",
	EMERGENCY_MEDICINE = "Emergency Medicine",
	INTERVENTIONAL_CARDIOLOGY = "Interventional Cardiology",
	CARDIOVASCULAR_DISEASE = "Cardiovascular Disease",
	NEUROLOGY = "Neurology",
	CANCER_CARE = "Cancer Care",
	MEDICAL_ONCOLOGY = "Medical Oncology",
	VASCULAR_SURGERY = "Vascular Surgery",
	NEPHROLOGY = "Nephrology",
	PHYSICAL_MEDICINE_AND_REHABILITATION = "Physical Medicine and Rehabilitation",
	DIAGNOSTIC_RADIOLOGY = "Diagnostic Radiology",
	PEDIATRICS = "Pediatrics",
	PEDIATRIC_EMERGENCY_MEDICINE = "Pediatric Emergency Medicine",
	VASCULAR_AND_INTERVENTIONAL_RADIOLOGY = "Vascular and Interventional Radiology",
	PEDIATRIC_SURGERY = "Pediatric Surgery",
	GENERAL_SURGERY = "General Surgery",
	TRANSPLANT_SURGERY = "Transplant Surgery",
	LIVER___ABDOMINAL_TRANSPLANT_SURGERY = "Liver & Abdominal Transplant Surgery",
	BLOOD_AND_MARROW_STEM_CELL_TRANSPLANTATION = "Blood and Marrow Stem Cell Transplantation",
	PRIMARY_CARE = "Primary Care",
	FAMILY_MEDICINE = "Family Medicine",
	PSYCHOLOGY = "Psychology",
	THORACIC_AND_CARDIAC_SURGERY = "Thoracic and Cardiac Surgery",
	CARDIAC_SURGERY = "Cardiac Surgery",
	PEDIATRIC_CONGENITAL_CARDIAC_SURGERY = "Pediatric/Congenital Cardiac Surgery",
	ANESTHESIOLOGY = "Anesthesiology",
	OTOLARYNGOLOGY_HEAD___NECK_SURGERY = "Otolaryngology-Head & Neck Surgery",
	PEDIATRIC_OTOLARYNGOLOGY = "Pediatric Otolaryngology",
	NEONATOLOGY = "Neonatology",
	PEDIATRIC_ENDOCRINOLOGY = "Pediatric Endocrinology",
	WOMEN_S_MENTAL_HEALTH = "Women's Mental Health",
	NURSE_PRACTITIONER = "Nurse Practitioner",
	ORTHOPEDIC_SURGERY = "Orthopedic Surgery",
	SHOULDER__ELBOW___SPORTS_MEDICINE = "Shoulder, Elbow & Sports Medicine",
	PATHOLOGY___ANATOMIC___CLINICAL = "Pathology - Anatomic & Clinical",
	CYTOPATHOLOGY = "Cytopathology",
	INFECTIOUS_DISEASE = "Infectious Disease",
	UROLOGY = "Urology",
	RHEUMATOLOGY = "Rheumatology",
	PEDIATRIC_GASTROENTEROLOGY = "Pediatric Gastroenterology",
	GASTROENTEROLOGY = "Gastroenterology",
	PATHOLOGY___MOLECULAR_GENETIC = "Pathology - Molecular Genetic",
	PATHOLOGY___ANATOMIC = "Pathology - Anatomic",
	REPRODUCTIVE_ENDOCRINOLOGY_INFERTILITY = "Reproductive Endocrinology/Infertility",
	RADIOLOGY = "Radiology",
	ADVANCED_HEART_FAILURE_AND_TRANSPLANT_CARDIOLOGY = "Advanced Heart Failure and Transplant Cardiology",
	PHYSICAL_THERAPY = "Physical Therapy",
	NEUROLOGY_WITH_SPECIAL_QUALIFICATION_IN_CHILD_NEUROLOGY = "Neurology with Special Qualification in Child Neurology",
	PEDIATRIC_NEUROLOGY = "Pediatric Neurology",
	SLEEP_MEDICINE = "Sleep Medicine",
	SURGERY = "Surgery",
	BREAST___SOFT_TISSUE_SURGERY = "Breast & Soft Tissue Surgery",
	OPHTHALMOLOGY = "Ophthalmology",
	CATARACT_SURGERY = "Cataract Surgery",
	MATERNAL___FETAL_MEDICINE = "Maternal & Fetal Medicine",
	RADIATION_ONCOLOGY = "Radiation Oncology",
	ADULT_NEPHROLOGY = "Adult Nephrology",
	HIP___KNEE_RECONSTRUCTION = "Hip & Knee Reconstruction",
	SPINE_SURGERY = "Spine Surgery",
	INTERVENTIONAL_SPINE_CARE = "Interventional Spine Care",
	HOSPICE_AND_PALLIATIVE_MEDICINE = "Hospice and Palliative Medicine",
	PSYCHIATRY = "Psychiatry",
	TRANSPLANT_HEPATOLOGY = "Transplant Hepatology",
	HOSPITAL_MEDICINE = "Hospital Medicine",
	PEDIATRIC_CARDIOLOGY = "Pediatric Cardiology",
	ENDOCRINOLOGY__DIABETES_AND_METABOLISM = "Endocrinology, Diabetes and Metabolism",
	SOCIAL_WORKER = "Social Worker",
	PEDIATRIC_ORTHOPEDICS = "Pediatric Orthopedics",
	SPORTS_MEDICINE = "Sports Medicine",
	NEUROLOGICAL_SURGERY = "Neurological Surgery",
	FEMALE_PELVIC_MEDICINE_AND_RECONSTRUCTIVE_SURGERY = "Female Pelvic Medicine and Reconstructive Surgery",
	PEDIATRIC_REHABILITATION_MEDICINE = "Pediatric Rehabilitation Medicine",
	PAIN_MEDICINE_MANAGEMENT = "Pain Medicine/Management",
	PEDIATRIC_UROLOGY = "Pediatric Urology",
	PEDIATRIC_RHEUMATOLOGY = "Pediatric Rheumatology",
	TRAUMA = "Trauma",
	GERIATRIC_MEDICINE = "Geriatric Medicine",
	CLINICAL_NEUROPHYSIOLOGY = "Clinical Neurophysiology",
	HEMATOLOGY_ONCOLOGY = "Hematology/Oncology",
	HEMATOLOGY = "Hematology",
	PROSTHODONTICS = "Prosthodontics",
	ENDOCRINOLOGY = "Endocrinology",
	PEDIATRIC_PULMONOLOGY = "Pediatric Pulmonology",
	PEDIATRICIAN__GENERAL_PEDIATRICS_ = "Pediatrician (General Pediatrics)",
	MIDWIFE = "Midwife",
	PEDIATRIC_HOSPITAL_MEDICINE = "Pediatric Hospital Medicine",
	PULMONOLOGY = "Pulmonology",
	CHILD_AND_ADOLESCENT_PSYCHIATRY = "Child and Adolescent Psychiatry",
	CRITICAL_CARE_MEDICINE = "Critical Care Medicine",
	SURGICAL_CRITICAL_CARE = "Surgical Critical Care",
	PEDIATRIC_NEPHROLOGY = "Pediatric Nephrology",
	PEDIATRIC_CRITICAL_CARE_MEDICINE = "Pediatric Critical Care Medicine",
	PEDIATRIC_INFECTIOUS_DISEASES = "Pediatric Infectious Diseases",
	COLON_AND_RECTAL_SURGERY = "Colon and Rectal Surgery",
	ELECTROPHYSIOLOGY_CARDIOLOGY = "Electrophysiology Cardiology",
	ALLERGY_AND_IMMUNOLOGY = "Allergy and Immunology",
	PEDIATRIC_ALLERGY_AND_IMMUNOLOGY = "Pediatric Allergy and Immunology",
	CLINICAL_GENETICS_AND_GENOMICS__MD_ = "Clinical Genetics and Genomics (MD)",
	NEURO_ONCOLOGY = "Neuro-Oncology",
	PEDIATRIC_ANESTHESIOLOGY = "Pediatric Anesthesiology",
	NEUROMUSCULAR_MEDICINE = "Neuromuscular Medicine",
	BARIATRIC_SURGERY = "Bariatric Surgery",
	AUDIOLOGY = "Audiology",
	NEURORADIOLOGY = "Neuroradiology",
	NEONATAL_PERINATAL_MEDICINE = "Neonatal-Perinatal Medicine",
	PEDIATRIC_OPHTHALMOLOGY = "Pediatric Ophthalmology",
	CLINICAL_INFORMATICS = "Clinical Informatics",
	HAND__ELBOW___MICROVASCULAR = "Hand, Elbow & Microvascular",
	PEDIATRIC_TRANSPLANT_HEPATOLOGY = "Pediatric Transplant Hepatology",
	NEUROLOGICAL_SPINE_SURGERY = "Neurological Spine Surgery",
	ENDOCRINE_SURGERY = "Endocrine Surgery",
	NEUROPATHOLOGY = "Neuropathology",
	THORACIC_SURGERY = "Thoracic Surgery",
	DENTISTRY = "Dentistry",
	COSMETIC_DENTISTRY = "Cosmetic Dentistry",
	GYNECOLOGIC_ONCOLOGY = "Gynecologic Oncology",
	PEDIATRIC_NEUROLOGICAL_SURGERY = "Pediatric Neurological Surgery",
	DERMATOLOGY = "Dermatology",
	MINIMALLY_INVASIVE_GYNECOLOGIC_SURGERY = "Minimally Invasive Gynecologic Surgery",
	UROLOGIC_ONCOLOGY = "Urologic Oncology",
	ADOLESCENT_MEDICINE = "Adolescent Medicine",
	CHILD_AND_ADOLESCENT_PSYCHOLOGY = "Child and Adolescent Psychology",
	STROKE___CEREBROVASCULAR_NEUROLOGY = "Stroke & Cerebrovascular Neurology",
	GENETIC_COUNSELING = "Genetic Counseling",
	ORTHOPEDIC_SPINE_SURGERY = "Orthopedic Spine Surgery",
	GENERAL_OPHTHALMOLOGY = "General Ophthalmology",
	GERIATRIC_PSYCHIATRY = "Geriatric Psychiatry",
	PERIODONTICS = "Periodontics",
	PATHOLOGY___HEMATOLOGY = "Pathology - Hematology",
	PLASTIC___RECONSTRUCTIVE_SURGERY = "Plastic & Reconstructive Surgery",
	NEUROTOLOGY = "Neurotology",
	PEDIATRIC_HEMATOLOGY_ONCOLOGY = "Pediatric Hematology-Oncology",
	PEDIATRIC_THORACIC_SURGERY = "Pediatric Thoracic Surgery",
	SURGICAL_ONCOLOGY = "Surgical Oncology",
	LGBTQ_MENTAL_HEALTH = "LGBTQ Mental Health",
	RECONSTRUCTIVE_UROLOGY = "Reconstructive Urology",
	UROGYNECOLOGY = "Urogynecology",
	ORAL_AND_MAXILLOFACIAL_SURGERY = "Oral and Maxillofacial Surgery",
	ORTHOPEDIC_SPORTS_MEDICINE = "Orthopedic Sports Medicine",
	NUCLEAR_CARDIOLOGY = "Nuclear Cardiology",
	INTERVENTIONAL_NEURORADIOLOGY = "Interventional Neuroradiology",
	PEDIATRIC_DERMATOLOGY = "Pediatric Dermatology",
	OPTOMETRY = "Optometry",
	SPEECH_LANGUAGE_PATHOLOGY = "Speech-Language Pathology",
	PRIMARY_CARE_INTERNIST = "Primary Care Internist",
	ADULT_CONGENITAL_HEART_DISEASE = "Adult Congenital Heart Disease",
	DERMATOPATHOLOGY = "Dermatopathology",
	PODIATRY = "Podiatry",
	PAIN_MEDICINE = "Pain Medicine",
	ORAL_PATHOLOGY = "Oral Pathology",
	ADDICTION_PSYCHIATRY = "Addiction Psychiatry",
	ORTHODONTICS = "Orthodontics",
	RHINOLOGY = "Rhinology",
	ADULT_CARDIAC_SURGERY = "Adult Cardiac Surgery",
	CLINICAL_NEUROPSYCHOLOGY = "Clinical Neuropsychology",
	NEUROPSYCHIATRY = "Neuropsychiatry",
	NUCLEAR_MEDICINE = "Nuclear Medicine",
	GENERAL_OBSTETRICS_AND_GYNECOLOGY = "General Obstetrics and Gynecology",
	PEDIATRIC_RADIOLOGY = "Pediatric Radiology",
	NEURO_RADIOLOGY = "Neuro Radiology",
	CRITICAL_CARE_NEUROLOGY = "Critical Care Neurology",
	FOOT___ANKLE = "Foot & Ankle",
	PEDIATRIC_SURGICAL_ONCOLOGY = "Pediatric Surgical Oncology",
	PEDIATRIC_NEUROSURGERY = "Pediatric Neurosurgery",
	NEUROENDOCRINOLOGY = "Neuroendocrinology",
	OPHTHALMIC_PLASTIC___RECONSTRUCTIVE_SURGERY = "Ophthalmic Plastic & Reconstructive Surgery",
	NEURO_OPHTHALMOLOGY = "Neuro-Ophthalmology",
	PATHOLOGY = "Pathology",
	ANATOMIC_PATHOLOGY_AND_CLINICAL_PATHOLOGY = "Anatomic Pathology and Clinical Pathology",
	MOLECULAR_PATHOLOGY = "Molecular Pathology",
	PREVENTIVE_MEDICINE = "Preventive Medicine",
	HEPATOLOGY = "Hepatology",
	HOSPITALIST = "Hospitalist",
	GENERAL_PEDIATRICS = "General Pediatrics",
	PULMONARY_CRITICAL_CARE_MEDICINE = "Pulmonary Critical Care Medicine",
	ORTHOGNATHIC_SURGERY = "Orthognathic Surgery",
	PEDIATRIC_DENTISTRY = "Pediatric Dentistry",
	ORAL_AND_MAXILLOFACIAL_RADIOLOGY = "Oral and Maxillofacial Radiology",
	ENDODONTICS = "Endodontics",
	ADULT_PSYCHIATRY = "Adult Psychiatry",
	PEDIATRIC_SLEEP_MEDICINE = "Pediatric Sleep Medicine",
	ELECTRODIAGNOSTIC_MEDICINE = "Electrodiagnostic Medicine",
	NEONATAL_THORACIC_SURGERY = "Neonatal Thoracic Surgery",
	PEDIATRIC_HEAD_AND_NECK_SURGERY = "Pediatric Head and Neck Surgery",
	ORTHOPEDICS = "Orthopedics",
	ORTHOPEDIC_ONCOLOGY = "Orthopedic Oncology",
	GENERAL_NEUROLOGY = "General Neurology",
	GASTROINTESTINAL_PATHOLOGY = "Gastrointestinal Pathology",
	OBSTETRICS = "Obstetrics",
	MATERNAL_AND_FETAL_MEDICINE = "Maternal and Fetal Medicine",
	MATERNAL_FETAL_MEDICINE = "Maternal-Fetal Medicine",
	NEUROSURGERY = "Neurosurgery",
	CARDIOTHORACIC_SURGERY = "Cardiothoracic Surgery",
	GENERAL_PSYCHIATRY = "General Psychiatry",
	PSYCHOTHERAPY = "Psychotherapy",
	OTOLARYNGOLOGY = "Otolaryngology",
	OTOLARYNGOLOGY___HEAD___NECK_SURGERY = "Otolaryngology - Head & Neck Surgery",
	HEAD_AND_NECK_SURGERY = "Head and Neck Surgery",
	SURGERY__NEUROLOGICAL = "Surgery, Neurological",
	REPRODUCTIVE_ENDOCRINOLOGY = "Reproductive Endocrinology",
	GYNECOLOGIC_ENDOCRINOLOGY = "Gynecologic Endocrinology",
	FACIAL_PLASTIC_AND_RECONSTRUCTIVE_SURGERY = "Facial Plastic and Reconstructive Surgery",
	OTOLARYNGOLOGY__ENT_ = "Otolaryngology (ENT)",
	ONCOLOGY = "Oncology",
	CHILD_NEUROLOGY = "Child Neurology",
	PEDIATRIC_HEMATOLOGY_AND_ONCOLOGY = "Pediatric Hematology and Oncology",
	PEDIATRIC_ONCOLOGY = "Pediatric Oncology",
	PEDIATRIC_HOSPITALIST = "Pediatric Hospitalist",
	HEART_SURGERY = "Heart Surgery",
	SURGERY__THORACIC_CARDIOVASCULAR = "Surgery, Thoracic Cardiovascular",
	ADULT_CARDIOTHORACIC_SURGERY = "Adult Cardiothoracic Surgery",
}

export interface TextLink {
	cta1Text?: string,
	cta1Link?: string,
}

export interface C_promo2 {
	title?: string,
	image?: Image,
	textLink?: TextLink,
}

export interface C_publications {
	title?: string,
	subtitle1?: string,
	subtitle2?: string,
}

export interface C_transitAdvisoryNoticeBannerCTALinkText {
	cta1Text?: string,
	cta1Link?: string,
}

export interface C_virtualVisitsContent {
	title?: string,
	description?: string,
	cta?: Cta,
}

export enum Type_2 {
	FELLOWSHIP = "Fellowship",
	RESIDENCY = "Residency",
	INTERNSHIP = "Internship",
	MEDICAL_SCHOOL = "Medical School",
}

export interface EducationList {
	type: Type_2,
	institutionName: string,
	yearCompleted: number,
}

export enum Type_3 {
	NONE = "None",
	BOOK_NOW = "Book Now",
	CALL_NOW = "Call Now",
	CONTACT_US = "Contact Us",
	SEND_MESSAGE = "Send Message",
	USE_APP = "Use App",
	PLAY_GAME = "Play Game",
	SHOP_NOW = "Shop Now",
	SIGN_UP = "Sign Up",
	WATCH_VIDEO = "Watch Video",
	SEND_EMAIL = "Send Email",
	LEARN_MORE = "Learn More",
	PURCHASE_GIFT_CARDS = "Purchase Gift Cards",
	ORDER_NOW = "Order Now",
	FOLLOW_PAGE = "Follow Page",
}

export interface FacebookCallToAction {
	type: Type_3,
	value?: string,
}

export interface FeaturedMessage {
	description?: string,
	url?: string,
}

export enum Gender {
	UNSPECIFIED = "Unspecified",
	FEMALE = "Female",
	MALE = "Male",
}

export enum Degrees {
	ANP = "Adult Nurse Practitioner (ANP)",
	APN = "Advanced Practice Nurse (APN)",
	APRN = "Advanced Practice Registered Nurse (APRN)",
	ARNP = "Advanced Registered Nurse Practitioner (ARNP)",
	AUD = "Audiologist (AUD)",
	BSW = "Bachelors of Social Work (BSW)",
	CCCA = "Certificate of Clinical Competence in Audiology (CCCA)",
	CNM = "Certified Nurse Midwife (CNM)",
	CNP = "Certified Nurse Practitioner (CNP)",
	CNS = "Clinical Nurse Specialist (CNS)",
	CPNP = "Certified Pediatric Nurse Practitioner (CPNP)",
	CRNA = "Certified Registered Nurse Anesthetist (CRNA)",
	CRNP = "Certified Registered Nurse Practitioner (CRNP)",
	DC = "Doctor of Chiropractic (DC)",
	DDS = "Doctor of Dental Surgery (DDS)",
	DMD = "Doctor of Dental Medicine (DMD)",
	DNP = "Doctor of Nursing Practice (DNP)",
	DO = "Doctor of Osteopathy (DO)",
	DPM = "Doctor of Podiatric Medicine (DPM)",
	DSW = "Doctorate Social Work (DSW)",
	DVM = "Doctor of Veterinary Medicine (DVM)",
	FNP = "Family Nurse Practitioner (FNP)",
	GNP = "Geriatric Nurse Practitioner (GNP)",
	LAC = "Licensed Acupuncturist (LAC)",
	LCSW = "Licensed Social Worker (LCSW)",
	LPN = "Licensed Practical Nurse (LPN)",
	MBA = "Master of Business Administration (MBA)",
	MBBS = "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
	MD = "Medical Doctor (MD)",
	MPH = "Master of Public Health (MPH)",
	MSW = "Master Social Work (MSW)",
	ND = "Naturopathic Doctor (ND)",
	NNP = "Neonatal Nurse Practitioner (NNP)",
	NP = "Nurse Practitioner (NP)",
	OD = "Doctor of Optometry (OD)",
	PA = "Physician Assistant (PA)",
	PAC = "Physician Assistant Certified (PAC)",
	PHARMD = "Doctor of Pharmacy (PHARMD)",
	PHD = "Doctor of Philosophy (PHD)",
	PNP = "Pediatric Nurse Practitioner (PNP)",
	PSYD = "Doctor of Psychology (PSYD)",
	RD = "Registered Dietician (RD)",
	RSW = "Registered Social Worker (RSW)",
	VMD = "Veterinary Medical Doctor (VMD)",
	WHNP = "Womens Health Nurse Practitioner (WHNP)",
}

export enum LocationType {
	LOCATION = "Location",
	HEALTHCARE_FACILITY = "Healthcare Facility",
	HEALTHCARE_PROFESSIONAL = "Healthcare Professional",
	ATM = "ATM",
	RESTAURANT = "Restaurant",
	HOTEL = "Hotel",
}

export interface MenuUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface OrderUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export enum PaymentOptions {
	ALIPAY = "Alipay",
	AMERICANEXPRESS = "American Express",
	ANDROIDPAY = "Google Pay",
	APPLEPAY = "Apple Pay",
	ATM = "ATM",
	ATMQUICK = "ATM Quick",
	BACS = "BACS",
	BANCONTACT = "Bancontact",
	BANKDEPOSIT = "Bank Deposit",
	BANKPAY = "Bank Pay",
	BGO = "Bank/Giro Overschrijving",
	BITCOIN = "Bitcoin",
	Bar = "Bargeld",
	CARTASI = "CartaSi",
	CASH = "Cash",
	CCS = "CCS",
	CHECK = "Check",
	CONB = "Contactloos betalen",
	CVVV = "Cadeaubon/VVV bon",
	DEBITNOTE = "Debit Note",
	DINERSCLUB = "Diners Club",
	DIRECTDEBIT = "Direct Debit",
	DISCOVER = "Discover",
	ECKARTE = "Girokarte",
	ECOCHEQUE = "EcoCheque",
	EKENA = "E-kena",
	EMV = "Elektronische Maaltijdcheques",
	FINANCING = "Financing",
	GOPAY = "GoPay",
	HAYAKAKEN = "Hayakaken",
	HEBAG = "He-Bag",
	IBOD = "iBOD",
	ICCARDS = "IC Cards",
	ICOCA = "Icoca",
	ID = "iD",
	IDEAL = "iDeal",
	INCA = "Incasso",
	INVOICE = "Invoice",
	JCB = "JCB",
	JCoinPay = "J−Coin Pay",
	JKOPAY = "JKO Pay",
	KITACA = "Kitaca",
	KLA = "Klantenkaart",
	KLARNA = "Klarna",
	LINEPAY = "LINE Pay",
	MAESTRO = "Maestro",
	MANACA = "Manaca",
	MASTERCARD = "MasterCard",
	MIPAY = "Mi Pay",
	MONIZZE = "Monizze",
	MPAY = "MPay",
	Manuelle_Lastsch = "Manuelle Lastschrift",
	Merpay = "メルPay",
	NANACO = "nanaco",
	NEXI = "Nexi",
	NIMOCA = "Nimoca",
	OREM = "Onder Rembours",
	PASMO = "Pasmo",
	PAYBACKPAY = "Payback Pay",
	PAYBOX = "Paybox",
	PAYCONIQ = "Payconiq",
	PAYPAL = "PayPal",
	PAYPAY = "PayPay",
	PAYSEC = "PaySec",
	PIN = "PIN",
	POSTEPAY = "Postepay",
	QRCODE = "QR Code Payment",
	QUICPAY = "QUICPay",
	RAKUTENEDY = "Rakuten Edy",
	RAKUTENPAY = "楽天Pay",
	SAMSUNGPAY = "Samsung Pay",
	SODEXO = "Sodexo",
	SUGOCA = "Sugoca",
	SUICA = "Suica",
	SWISH = "Swish",
	TICKETRESTAURANT = "Ticket Restaurant",
	TOICA = "Toica",
	TRAVELERSCHECK = "Traveler's Check",
	TSCUBIC = "TS CUBIC",
	TWINT = "Twint",
	UNIONPAY = "China UnionPay",
	VEV = "Via een verzekering",
	VISA = "Visa",
	VISAELECTRON = "Visa Electron",
	VOB = "Vooruit betalen",
	VOUCHER = "Voucher",
	VPAY = "V PAY",
	WAON = "WAON",
	WECHATPAY = "WeChat Pay",
	WIRETRANSFER = "Wire Transfer",
	Yucho_Pay = "ゆうちょPay",
	ZELLE = "Zelle",
	AuPay = "auPay",
	DBarai = "d払い ",
	Überweisung = "Banküberweisung",
}

export enum PriceRange {
	UNSPECIFIED = "Unspecified",
	ONE = "$",
	TWO = "$$",
	THREE = "$$$",
	FOUR = "$$$$",
}

export interface RankTrackingCompetitors {
	name: string,
	website: string,
}

export enum RankTrackingFrequency {
	WEEKLY = "Weekly",
	MONTHLY = "Monthly",
	QUARTERLY = "Quarterly",
}

export enum RankTrackingKeywords {
	NAME = "Name",
	PRIMARY_CATEGORY = "Primary Category",
	SECONDARY_CATEGORY = "Secondary Category",
}

export enum RankTrackingQueryTemplates {
	KEYWORD = "Keyword",
	KEYWORD_ZIP = "Keyword Zip",
	KEYWORD_CITY = "Keyword City",
	KEYWORD_IN_CITY = "Keyword in City",
	KEYWORD_NEAR_ME = "Keyword near me",
	KEYWORD_CITY_STATE = "Keyword City State",
}

export enum RankTrackingSites {
	GOOGLE_DESKTOP = "Google Desktop",
	GOOGLE_MOBILE = "Google Mobile",
	BING_DESKTOP = "Bing Desktop",
	BING_MOBILE = "Bing Mobile",
	YAHOO_DESKTOP = "Yahoo Desktop",
	YAHOO_MOBILE = "Yahoo Mobile",
}

export interface ReservationUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface ServiceArea {
	places?: string[],
}

export enum Presentation {
	BUTTON = "Button",
	LINK = "Link",
}

export interface UberLink {
	text?: string,
	presentation: Presentation,
}

export interface UberTripBranding {
	text: string,
	url: string,
	description: string,
}

export interface WebsiteUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface ComplexVideo {
	url: string,
	video?: string,
	description?: string,
}

export interface HealthcareProfessional {
	bingWebsiteOverride?: string,
	questionsAndAnswers?: boolean,
	covid19InformationUrl?: string,
	covidMessaging?: string,
	facebookAbout?: string,
	facebookWebsiteOverride?: string,
	frequentlyAskedQuestions?: FrequentlyAskedQuestions[],
	geomodifier?: string,
	googleEntityRelationship?: GoogleEntityRelationship,
	googleMyBusinessLabels?: string[],
	googlePlaceId?: string,
	googleShortName?: string,
	holidayHoursConversationEnabled?: boolean,
	impressum?: string,
	landingPageUrl?: string,
	linkedInUrl?: string,
	neighborhood?: string,
	nudgeEnabled?: boolean,
	onlineServiceHours?: Hours,
	primaryConversationContact?: any,
	reviewResponseConversationEnabled?: boolean,
	serviceAreaPlaces?: ServiceAreaPlaces[],
	slug?: string,
	telehealthUrl?: string,
	what3WordsAddress?: string,
	yelpWebsiteOverride?: string,
	acceptingNewPatients?: boolean,
	additionalHoursText?: string,
	address: Address,
	addressHidden?: boolean,
	alternatePhone?: any,
	associations?: string[],
	brands?: string[],
	description?: string,
	hours?: Hours,
	logo?: ComplexImage,
	name: string,
	categories?: any,
	certifications?: string[],
	cityCoordinate?: Coordinate,
	closed?: boolean,
	clusterIndex?: number,
	conditionsTreated?: string[],
	c_aboutSectionTitle?: string,
	c_aboutSectionVideo?: C_aboutSectionVideo,
	c_academicAppointments?: string[],
	c_activeOnPages?: boolean,
	c_additionalProviderLocations?: EntityReference[],
	c_affiliated?: boolean,
	c_affiliations?: C_affiliations[],
	c_alertBannerBackgroundColor?: string,
	c_alertBannerCTAText?: string,
	c_alertBannerCTAURL?: string,
	c_alertBannerFontColor?: string,
	c_alertBannerText?: string,
	c_alertBannerTitle?: string,
	c_appointmentPhone?: number,
	c_availableInPersonAppointmentTimes?: string[],
	c_availableVirtualAppointmentTimes?: string[],
	c_awards?: string[],
	c_awardsRT?: string[],
	c_baseURL?: string,
	c_billingPhone?: number,
	c_binaryFountainHide?: boolean,
	c_bingWebsiteOverride?: string,
	c_boardCertifiedSpecialties?: C_boardCertifiedSpecialties[],
	c_centersInstitutesAndPrograms?: C_centersInstitutesAndPrograms[],
	c_columbiaDoctor?: boolean,
	c_columbiaETL?: boolean,
	c_columbiaPages?: boolean,
	c_columbiaSecondOpinion?: boolean,
	c_columbiaSecondOpinionID?: string,
	c_cornellDoctor?: boolean,
	c_cTA1LinkText?: C_cTA1LinkText,
	c_cTA2LinkText?: C_cTA2LinkText,
	c_cTA2SecondOpinionID?: string,
	c_cUIMCAboutSectionVideo?: C_cUIMCAboutSectionVideo,
	c_cUIMCApptTile1?: C_cUIMCApptTile1,
	c_cUIMCApptTile2?: C_cUIMCApptTile2,
	c_cUIMCApptTile3?: C_cUIMCApptTile3,
	c_cUIMCBillingNumber?: string,
	c_cUIMCBookOnlineID?: string,
	c_cUIMCBookOnlineIDShow?: boolean,
	c_cUIMCCTA1?: C_cUIMCCTA1,
	c_cUIMCFullName?: string,
	c_cUIMCInsuranceList?: C_cUIMCInsuranceList[],
	c_cUIMCInsurancesFilter?: C_cUIMCInsurancesFilter[],
	c_cUIMCOfficeName?: string,
	c_cUIMCPagesMetaDescription?: string,
	c_cUIMCPagesMetaTitle?: string,
	c_cUIMCPagesURL?: string,
	c_cUIMCPrimarySpecialty?: C_cUIMCPrimarySpecialty[],
	c_cUIMCPrimarySpecialtyEntity?: EntityReference[],
	c_cUIMCPrimaryTitle?: string,
	c_cUIMCTempPrimaryLocation?: boolean,
	c_cUIMCVirtualVisitLocatorDisplayName?: string,
	c_cUIMCVirtualVisits?: boolean,
	c_departments?: string[],
	c_doximityTrackingPhone?: string,
	c_educationInfo?: C_educationInfo[],
	c_eMRIDSERid?: string,
	c_epicSchedulerDepartmentIDs?: string[],
	c_exemptFromETL?: boolean,
	c_existingPatientPhone?: number,
	c_expertiseFilter?: C_expertiseFilter[],
	c_expertises?: string[],
	c_folderLevel1?: string,
	c_folderLevel2?: string,
	c_folderLevel3?: string,
	c_folderLevel4?: string,
	c_fullName?: string,
	c_gMBTrackingTag?: string,
	c_googleStoreCode?: string,
	c_grants?: C_grants[],
	c_grantsRT?: string[],
	c_grantsList?: string,
	c_groupCode?: C_groupCode[],
	c_hospitalAffiliationsWebMD?: string[],
	c_hospitalAndMedGroupLocator?: C_hospitalAndMedGroupLocator[],
	c_hospitalsLocatorInternal?: string[],
	c_hudsonURL?: string,
	c_insuranceSubText?: string,
	c_insurancesFilter?: C_insurancesFilter[],
	c_languagesFilter?: C_languagesFilter[],
	c_lawrenceURL?: string,
	c_listingsLaunchURL?: string,
	c_locationHours?: Hours,
	c_methodistURL?: string,
	c_mGBrooklynURL?: string,
	c_mGHudsonURL?: string,
	c_mGQueensURL?: string,
	c_mGWestURL?: string,
	c_newPatientPhone?: number,
	c_nYPPages?: boolean,
	c_nYPVanityURL?: string,
	c_nYPVanityURLText?: string,
	c_nYPVirtualVisits?: boolean,
	c_nYPMGSpecificOpenSchedulingOptions?: C_nYPMGSpecificOpenSchedulingOptions[],
	c_oldEntityID?: string,
	c_openScheduling?: boolean,
	c_openSchedulingOptions?: C_openSchedulingOptions[],
	c_originalURL?: string,
	c_otherTrackingTag?: string,
	c_pagesLinkedInURL?: string,
	c_pagesMetaDescription?: string,
	c_pagesMetaTitle?: string,
	c_pagesURL?: string,
	c_pagesYouTubeURL?: string,
	c_pediatric?: boolean,
	c_phyndProviderID?: string,
	c_practiceName?: string,
	c_primaryLocation?: boolean,
	c_primarySpecialties?: C_primarySpecialties[],
	c_primarySpecialtyPhynd?: C_primarySpecialtyPhynd[],
	c_promo1Header?: string,
	c_promo1List?: string[],
	c_promo2?: C_promo2,
	c_providerContactID?: string,
	c_publications?: C_publications[],
	c_publicationsRT?: string[],
	c_publicationsList?: string[],
	c_pubMedURL?: string,
	c_queensURL?: string,
	c_researchInterests?: string[],
	c_reservationBaseURL?: string,
	c_reservationTrackingTag?: string,
	c_richTextDescription?: string,
	c_shortName?: string,
	c_showBadge1?: boolean,
	c_showBadge2?: boolean,
	c_showBookOnlineID?: string,
	c_showBookOnlineWidget?: boolean,
	c_specialtyEntityList?: EntityReference[],
	c_transitAdvisoryNoticeBanner?: string,
	c_transitAdvisoryNoticeBannerCTALinkText?: C_transitAdvisoryNoticeBannerCTALinkText,
	c_virtualVisitsContent?: C_virtualVisitsContent,
	c_voluntaryProvider?: boolean,
	c_wCOpenScheduleURL?: string,
	c_webMDCareFinderProgram?: boolean,
	c_webMDSponsorID?: string,
	c_webMDTrackingPhone?: string,
	c_zocDocDescription?: string,
	c_zocDocID?: string,
	c_zocDocTitle?: string,
	c_zocDocURL?: string,
	firstPartyReviewPage?: any,
	reviewGenerationUrl?: any,
	defaultReviewInviteTemplate?: any,
	displayCoordinate?: Coordinate,
	dropoffCoordinate?: Coordinate,
	educationList?: EducationList[],
	emails?: string[],
	facebookOverrideCity?: string,
	facebookCoverPhoto?: Image,
	facebookCallToAction?: FacebookCallToAction,
	facebookDescriptor?: string,
	facebookEmail?: string,
	facebookLinkedAccount?: any,
	facebookName?: string,
	facebookPageUrl?: string,
	facebookParentPageId?: string,
	facebookProfilePhoto?: Image,
	facebookStoreId?: string,
	facebookVanityUrl?: string,
	fax?: any,
	featuredMessage?: FeaturedMessage,
	firstName?: string,
	foursquareLinkedAccount?: any,
	photoGallery?: ComplexImage[],
	gender?: Gender,
	geocodedCoordinate?: Coordinate,
	gmbLinkedAccount?: any,
	googleAccountId?: string,
	googleAttributes?: any,
	googleCoverPhoto?: Image,
	googleProfilePhoto?: Image,
	googleWebsiteOverride?: string,
	headshot?: Image,
	admittingHospitals?: string[],
	degrees?: Degrees[],
	insuranceAccepted?: string[],
	instagramHandle?: string,
	isClusterPrimary?: boolean,
	isoRegionCode?: string,
	keywords?: string[],
	languages?: string[],
	lastName?: string,
	localPhone?: any,
	locationType?: LocationType,
	mainPhone?: any,
	menuUrl?: MenuUrl,
	middleName?: string,
	mobilePhone?: any,
	npi?: string,
	officeName?: string,
	orderUrl?: OrderUrl,
	paymentOptions?: PaymentOptions[],
	phones?: any,
	pickupCoordinate?: Coordinate,
	priceRange?: PriceRange,
	alternateNames?: string[],
	alternateWebsites?: string[],
	rankTrackingCompetitors?: RankTrackingCompetitors[],
	customKeywords?: string[],
	rankTrackingEnabled?: boolean,
	rankTrackingFrequency?: RankTrackingFrequency,
	rankTrackingKeywords?: RankTrackingKeywords[],
	rankTrackingQueryTemplates?: RankTrackingQueryTemplates[],
	rankTrackingSites?: RankTrackingSites[],
	reservationUrl?: ReservationUrl,
	routableCoordinate?: Coordinate,
	serviceArea?: ServiceArea,
	services?: string[],
	shortName35?: string,
	shortName64?: string,
	id: string,
	timezone?: any,
	tollFreePhone?: any,
	ttyPhone?: any,
	twitterHandle?: string,
	uberClientId?: string,
	uberLink?: UberLink,
	uberTripBranding?: UberTripBranding,
	walkableCoordinate?: Coordinate,
	websiteUrl?: WebsiteUrl,
	yearEstablished?: number,
	yextDisplayCoordinate?: Coordinate,
	yextDropoffCoordinate?: Coordinate,
	yextPickupCoordinate?: Coordinate,
	yextRoutableCoordinate?: Coordinate,
	yextWalkableCoordinate?: Coordinate,
	videos?: ComplexVideo[],
}
